-- +goose NO TRANSACTION
-- +goose Up
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SKILL_REQUEST_APPROVED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SKILL_REQUEST_REJECTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ROADMAP_REQUEST_APPROVED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ROADMAP_REQUEST_REJECTED';

-- +goose Down
SELECT 1;
