-- +goose NO TRANSACTION
-- +goose Up
ALTER TYPE catalog_request_status ADD VALUE IF NOT EXISTS 'GENERATING';
ALTER TYPE catalog_request_status ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE pod_quiz_status ADD VALUE IF NOT EXISTS 'GENERATING';
ALTER TYPE pod_quiz_status ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SKILL_REQUEST_READY';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'SKILL_REQUEST_FAILED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ROADMAP_REQUEST_READY';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ROADMAP_REQUEST_FAILED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'QUIZ_READY';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'QUIZ_FAILED';

-- +goose Down
SELECT 1;
