// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserIsAdminByPublicID = `-- name: GetUserIsAdminByPublicID :one
SELECT role = 'ADMIN' AS is_admin
FROM users
WHERE public_id = $1
  AND is_deleted = FALSE
`

func (q *Queries) GetUserIsAdminByPublicID(ctx context.Context, publicID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getUserIsAdminByPublicID, publicID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const setUsersAdminByUsernames = `-- name: SetUsersAdminByUsernames :exec
UPDATE users
SET role = 'ADMIN',
    updated_at = NOW()
WHERE username = ANY($1::citext[])
  AND is_deleted = FALSE
`

func (q *Queries) SetUsersAdminByUsernames(ctx context.Context, usernames []string) error {
	_, err := q.db.Exec(ctx, setUsersAdminByUsernames, usernames)
	return err
}
