// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveActiveRoadmapVersions = `-- name: ArchiveActiveRoadmapVersions :exec
UPDATE roadmap_version
SET status = 'ARCHIVED'
WHERE roadmap_id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) ArchiveActiveRoadmapVersions(ctx context.Context, roadmapID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, archiveActiveRoadmapVersions, roadmapID)
	return err
}

const createCommunity = `-- name: CreateCommunity :one
INSERT INTO community (skill_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, skill_id, name, description, created_at, updated_at
`

type CreateCommunityParams struct {
	SkillID     int64
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, createCommunity, arg.SkillID, arg.Name, arg.Description)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommunityChannel = `-- name: CreateCommunityChannel :one
INSERT INTO community_channel (community_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, community_id, name, description, created_at, updated_at, slug
`

type CreateCommunityChannelParams struct {
	CommunityID int64
	Name        string
	Slug        string
	Description pgtype.Text
}

func (q *Queries) CreateCommunityChannel(ctx context.Context, arg CreateCommunityChannelParams) (CommunityChannel, error) {
	row := q.db.QueryRow(ctx, createCommunityChannel,
		arg.CommunityID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i CommunityChannel
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (
    roadmap_version_id,
    title,
    description,
    estimated_hours,
    order_index,
    difficulty,
    slug,
    chapter,
    kind
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, roadmap_version_id, title, description, estimated_hours, order_index, difficulty, created_at, updated_at, slug, chapter, kind
`

type CreateMilestoneParams struct {
	RoadmapVersionID pgtype.Int8
	Title            string
	Description      pgtype.Text
	EstimatedHours   pgtype.Int4
	OrderIndex       int32
	Difficulty       pgtype.Text
	Slug             string
	Chapter          pgtype.Text
	Kind             string
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.RoadmapVersionID,
		arg.Title,
		arg.Description,
		arg.EstimatedHours,
		arg.OrderIndex,
		arg.Difficulty,
		arg.Slug,
		arg.Chapter,
		arg.Kind,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.RoadmapVersionID,
		&i.Title,
		&i.Description,
		&i.EstimatedHours,
		&i.OrderIndex,
		&i.Difficulty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Chapter,
		&i.Kind,
	)
	return i, err
}

const createRoadmap = `-- name: CreateRoadmap :one
INSERT INTO roadmaps (skill_id)
VALUES ($1)
RETURNING id, current_version_id, skill_id, created_at, updated_at
`

func (q *Queries) CreateRoadmap(ctx context.Context, skillID int64) (Roadmap, error) {
	row := q.db.QueryRow(ctx, createRoadmap, skillID)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.CurrentVersionID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoadmapVersion = `-- name: CreateRoadmapVersion :one
INSERT INTO roadmap_version (
    roadmap_id,
    version_number,
    status,
    generated_by,
    published_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, roadmap_id, version_number, status, generated_by, published_at, created_at
`

type CreateRoadmapVersionParams struct {
	RoadmapID     pgtype.Int8
	VersionNumber int32
	Status        CurrentStatus
	GeneratedBy   string
	PublishedAt   pgtype.Timestamptz
}

func (q *Queries) CreateRoadmapVersion(ctx context.Context, arg CreateRoadmapVersionParams) (RoadmapVersion, error) {
	row := q.db.QueryRow(ctx, createRoadmapVersion,
		arg.RoadmapID,
		arg.VersionNumber,
		arg.Status,
		arg.GeneratedBy,
		arg.PublishedAt,
	)
	var i RoadmapVersion
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name, slug, description, is_active)
VALUES ($1, $2, $3, TRUE)
RETURNING id, name, slug, description, is_active, created_at, updated_at
`

type CreateSkillParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.Name, arg.Slug, arg.Description)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCatalogRoadmapVersionBySkillID = `-- name: GetActiveCatalogRoadmapVersionBySkillID :one
SELECT
    rv.id,
    rv.roadmap_id,
    rv.version_number,
    rv.status,
    rv.generated_by,
    rv.published_at,
    rv.created_at
FROM roadmap_version rv
INNER JOIN roadmaps r ON r.id = rv.roadmap_id
WHERE r.skill_id = $1
  AND rv.status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveCatalogRoadmapVersionBySkillID(ctx context.Context, skillID int64) (RoadmapVersion, error) {
	row := q.db.QueryRow(ctx, getActiveCatalogRoadmapVersionBySkillID, skillID)
	var i RoadmapVersion
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxRoadmapVersionNumber = `-- name: GetMaxRoadmapVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int AS max_version
FROM roadmap_version
WHERE roadmap_id = $1
`

func (q *Queries) GetMaxRoadmapVersionNumber(ctx context.Context, roadmapID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxRoadmapVersionNumber, roadmapID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const listSimilarSkills = `-- name: ListSimilarSkills :many
SELECT
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    similarity(name, $1::text) AS score
FROM skills
WHERE is_active = TRUE
  AND (
    similarity(name, $1::text) >= $2::float4
    OR name ILIKE '%' || $1::text || '%'
  )
ORDER BY score DESC, name ASC
LIMIT $3
`

type ListSimilarSkillsParams struct {
	Query       string
	MinScore    float32
	ResultLimit int32
}

type ListSimilarSkillsRow struct {
	ID          int64
	Name        string
	Slug        string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Score       float32
}

func (q *Queries) ListSimilarSkills(ctx context.Context, arg ListSimilarSkillsParams) ([]ListSimilarSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSimilarSkills, arg.Query, arg.MinScore, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSimilarSkillsRow
	for rows.Next() {
		var i ListSimilarSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsEnrolledInSkill = `-- name: ListUserIDsEnrolledInSkill :many
SELECT user_id
FROM userskill
WHERE skill_id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) ListUserIDsEnrolledInSkill(ctx context.Context, skillID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDsEnrolledInSkill, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoadmapCurrentVersion = `-- name: SetRoadmapCurrentVersion :exec
UPDATE roadmaps
SET current_version_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetRoadmapCurrentVersionParams struct {
	ID               int64
	CurrentVersionID pgtype.Int8
}

func (q *Queries) SetRoadmapCurrentVersion(ctx context.Context, arg SetRoadmapCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setRoadmapCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}
