// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelByCommunityIDAndSlug = `-- name: GetChannelByCommunityIDAndSlug :one
SELECT id, community_id, name, slug, description, created_at, updated_at
FROM community_channel
WHERE community_id = $1
  AND slug = $2
`

type GetChannelByCommunityIDAndSlugParams struct {
	CommunityID int64
	Slug        string
}

type GetChannelByCommunityIDAndSlugRow struct {
	ID          int64
	CommunityID int64
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetChannelByCommunityIDAndSlug(ctx context.Context, arg GetChannelByCommunityIDAndSlugParams) (GetChannelByCommunityIDAndSlugRow, error) {
	row := q.db.QueryRow(ctx, getChannelByCommunityIDAndSlug, arg.CommunityID, arg.Slug)
	var i GetChannelByCommunityIDAndSlugRow
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBySkillSlugAndChannelSlug = `-- name: GetChannelBySkillSlugAndChannelSlug :one
SELECT
    cc.id,
    cc.community_id,
    cc.name,
    cc.slug,
    cc.description,
    cc.created_at,
    cc.updated_at,
    c.skill_id,
    s.slug AS skill_slug
FROM community_channel cc
INNER JOIN community c ON c.id = cc.community_id
INNER JOIN skills s ON s.id = c.skill_id
WHERE s.slug = $1
  AND cc.slug = $2
`

type GetChannelBySkillSlugAndChannelSlugParams struct {
	SkillSlug   string
	ChannelSlug string
}

type GetChannelBySkillSlugAndChannelSlugRow struct {
	ID          int64
	CommunityID int64
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SkillID     int64
	SkillSlug   string
}

func (q *Queries) GetChannelBySkillSlugAndChannelSlug(ctx context.Context, arg GetChannelBySkillSlugAndChannelSlugParams) (GetChannelBySkillSlugAndChannelSlugRow, error) {
	row := q.db.QueryRow(ctx, getChannelBySkillSlugAndChannelSlug, arg.SkillSlug, arg.ChannelSlug)
	var i GetChannelBySkillSlugAndChannelSlugRow
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SkillID,
		&i.SkillSlug,
	)
	return i, err
}

const listChannelsByCommunityID = `-- name: ListChannelsByCommunityID :many

SELECT id, community_id, name, slug, description, created_at, updated_at
FROM community_channel
WHERE community_id = $1
ORDER BY created_at ASC, id ASC
`

type ListChannelsByCommunityIDRow struct {
	ID          int64
	CommunityID int64
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// =========================================
// COMMUNITY CHANNELS
// =========================================
func (q *Queries) ListChannelsByCommunityID(ctx context.Context, communityID int64) ([]ListChannelsByCommunityIDRow, error) {
	rows, err := q.db.Query(ctx, listChannelsByCommunityID, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByCommunityIDRow
	for rows.Next() {
		var i ListChannelsByCommunityIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
