// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommunityBySkillID = `-- name: GetCommunityBySkillID :one

SELECT c.id, c.skill_id, c.name, c.description, c.created_at, c.updated_at,
       s.slug AS skill_slug
FROM community c
INNER JOIN skills s ON s.id = c.skill_id
WHERE c.skill_id = $1
`

type GetCommunityBySkillIDRow struct {
	ID          int64
	SkillID     int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SkillSlug   string
}

// =========================================
// GET
// =========================================
func (q *Queries) GetCommunityBySkillID(ctx context.Context, skillID int64) (GetCommunityBySkillIDRow, error) {
	row := q.db.QueryRow(ctx, getCommunityBySkillID, skillID)
	var i GetCommunityBySkillIDRow
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SkillSlug,
	)
	return i, err
}

const getCommunityBySkillSlug = `-- name: GetCommunityBySkillSlug :one
SELECT c.id, c.skill_id, c.name, c.description, c.created_at, c.updated_at,
       s.slug AS skill_slug
FROM community c
INNER JOIN skills s ON s.id = c.skill_id
WHERE s.slug = $1
`

type GetCommunityBySkillSlugRow struct {
	ID          int64
	SkillID     int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SkillSlug   string
}

func (q *Queries) GetCommunityBySkillSlug(ctx context.Context, slug string) (GetCommunityBySkillSlugRow, error) {
	row := q.db.QueryRow(ctx, getCommunityBySkillSlug, slug)
	var i GetCommunityBySkillSlugRow
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SkillSlug,
	)
	return i, err
}
