// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationOTP = `-- name: ConsumeEmailVerificationOTP :one

UPDATE email_verification_otp
SET consumed_at = NOW()
WHERE id = $1
  AND consumed_at IS NULL
RETURNING id, user_id, otp_hash, expires_at, consumed_at, created_at
`

// =========================================
// UPDATE
// =========================================
func (q *Queries) ConsumeEmailVerificationOTP(ctx context.Context, id int64) (EmailVerificationOtp, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationOTP, id)
	var i EmailVerificationOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailVerificationOTP = `-- name: CreateEmailVerificationOTP :one

INSERT INTO email_verification_otp (
    user_id,
    otp_hash,
    expires_at
)
VALUES ($1, $2, $3)
RETURNING id, user_id, otp_hash, expires_at, consumed_at, created_at
`

type CreateEmailVerificationOTPParams struct {
	UserID    int64
	OtpHash   string
	ExpiresAt pgtype.Timestamptz
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateEmailVerificationOTP(ctx context.Context, arg CreateEmailVerificationOTPParams) (EmailVerificationOtp, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationOTP, arg.UserID, arg.OtpHash, arg.ExpiresAt)
	var i EmailVerificationOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEmailVerificationOTPByUserID = `-- name: GetActiveEmailVerificationOTPByUserID :one

SELECT id, user_id, otp_hash, expires_at, consumed_at, created_at
FROM email_verification_otp
WHERE user_id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

// =========================================
// GET
// =========================================
func (q *Queries) GetActiveEmailVerificationOTPByUserID(ctx context.Context, userID int64) (EmailVerificationOtp, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerificationOTPByUserID, userID)
	var i EmailVerificationOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateActiveEmailVerificationOTPs = `-- name: InvalidateActiveEmailVerificationOTPs :exec
UPDATE email_verification_otp
SET consumed_at = NOW()
WHERE user_id = $1
  AND consumed_at IS NULL
`

func (q *Queries) InvalidateActiveEmailVerificationOTPs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailVerificationOTPs, userID)
	return err
}
