// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPodMembership = `-- name: CreatePodMembership :one

INSERT INTO pod_membership (
    pod_id,
    user_id,
    status,
    role,
    joined_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pod_id, user_id, status, joined_at, created_at, role
`

type CreatePodMembershipParams struct {
	PodID    int64
	UserID   int64
	Status   UserPodMembershipStatus
	Role     PodMemberRole
	JoinedAt pgtype.Timestamptz
}

// =========================================
// POD MEMBERSHIP
// =========================================
func (q *Queries) CreatePodMembership(ctx context.Context, arg CreatePodMembershipParams) (PodMembership, error) {
	row := q.db.QueryRow(ctx, createPodMembership,
		arg.PodID,
		arg.UserID,
		arg.Status,
		arg.Role,
		arg.JoinedAt,
	)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getAcceptedPodMembershipByUserID = `-- name: GetAcceptedPodMembershipByUserID :one
SELECT id, pod_id, user_id, status, joined_at, created_at, role
FROM pod_membership
WHERE user_id = $1
  AND status = 'ACCEPTED'
LIMIT 1
`

func (q *Queries) GetAcceptedPodMembershipByUserID(ctx context.Context, userID int64) (PodMembership, error) {
	row := q.db.QueryRow(ctx, getAcceptedPodMembershipByUserID, userID)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getPodMembershipByPodAndUser = `-- name: GetPodMembershipByPodAndUser :one
SELECT id, pod_id, user_id, status, joined_at, created_at, role
FROM pod_membership
WHERE pod_id = $1
  AND user_id = $2
`

type GetPodMembershipByPodAndUserParams struct {
	PodID  int64
	UserID int64
}

func (q *Queries) GetPodMembershipByPodAndUser(ctx context.Context, arg GetPodMembershipByPodAndUserParams) (PodMembership, error) {
	row := q.db.QueryRow(ctx, getPodMembershipByPodAndUser, arg.PodID, arg.UserID)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listAcceptedAdminsByPodID = `-- name: ListAcceptedAdminsByPodID :many
SELECT id, pod_id, user_id, status, joined_at, created_at, role
FROM pod_membership
WHERE pod_id = $1
  AND status = 'ACCEPTED'
  AND role = 'ADMIN'
ORDER BY joined_at ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListAcceptedAdminsByPodID(ctx context.Context, podID int64) ([]PodMembership, error) {
	rows, err := q.db.Query(ctx, listAcceptedAdminsByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodMembership
	for rows.Next() {
		var i PodMembership
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcceptedMembersByPodID = `-- name: ListAcceptedMembersByPodID :many
SELECT
    pm.id,
    pm.pod_id,
    pm.user_id,
    pm.status,
    pm.joined_at,
    pm.created_at,
    pm.role,
    u.username,
    u.name AS user_name
FROM pod_membership pm
INNER JOIN users u ON u.id = pm.user_id
WHERE pm.pod_id = $1
  AND pm.status = 'ACCEPTED'
ORDER BY
    CASE pm.role
        WHEN 'OWNER' THEN 0
        WHEN 'ADMIN' THEN 1
        ELSE 2
    END,
    pm.joined_at ASC NULLS LAST,
    pm.created_at ASC
`

type ListAcceptedMembersByPodIDRow struct {
	ID        int64
	PodID     int64
	UserID    int64
	Status    UserPodMembershipStatus
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Role      PodMemberRole
	Username  string
	UserName  string
}

func (q *Queries) ListAcceptedMembersByPodID(ctx context.Context, podID int64) ([]ListAcceptedMembersByPodIDRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedMembersByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedMembersByPodIDRow
	for rows.Next() {
		var i ListAcceptedMembersByPodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.Role,
			&i.Username,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcceptedMembersExcludingUser = `-- name: ListAcceptedMembersExcludingUser :many
SELECT id, pod_id, user_id, status, joined_at, created_at, role
FROM pod_membership
WHERE pod_id = $1
  AND status = 'ACCEPTED'
  AND user_id <> $2
ORDER BY joined_at ASC NULLS LAST, created_at ASC
`

type ListAcceptedMembersExcludingUserParams struct {
	PodID  int64
	UserID int64
}

func (q *Queries) ListAcceptedMembersExcludingUser(ctx context.Context, arg ListAcceptedMembersExcludingUserParams) ([]PodMembership, error) {
	rows, err := q.db.Query(ctx, listAcceptedMembersExcludingUser, arg.PodID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodMembership
	for rows.Next() {
		var i PodMembership
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembersByPodID = `-- name: ListPendingMembersByPodID :many
SELECT
    pm.id,
    pm.pod_id,
    pm.user_id,
    pm.status,
    pm.joined_at,
    pm.created_at,
    pm.role,
    u.username,
    u.name AS user_name
FROM pod_membership pm
INNER JOIN users u ON u.id = pm.user_id
WHERE pm.pod_id = $1
  AND pm.status = 'PENDING'
ORDER BY pm.created_at ASC
`

type ListPendingMembersByPodIDRow struct {
	ID        int64
	PodID     int64
	UserID    int64
	Status    UserPodMembershipStatus
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Role      PodMemberRole
	Username  string
	UserName  string
}

func (q *Queries) ListPendingMembersByPodID(ctx context.Context, podID int64) ([]ListPendingMembersByPodIDRow, error) {
	rows, err := q.db.Query(ctx, listPendingMembersByPodID, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMembersByPodIDRow
	for rows.Next() {
		var i ListPendingMembersByPodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.Role,
			&i.Username,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodMembershipsByUserID = `-- name: ListPodMembershipsByUserID :many
SELECT
    pm.id,
    pm.pod_id,
    pm.user_id,
    pm.status,
    pm.joined_at,
    pm.created_at,
    pm.role,
    p.slug AS pod_slug,
    p.name AS pod_name,
    s.slug AS skill_slug,
    s.name AS skill_name
FROM pod_membership pm
INNER JOIN pods p ON p.id = pm.pod_id
INNER JOIN skills s ON s.id = p.skill_id
WHERE pm.user_id = $1
ORDER BY pm.created_at DESC
`

type ListPodMembershipsByUserIDRow struct {
	ID        int64
	PodID     int64
	UserID    int64
	Status    UserPodMembershipStatus
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Role      PodMemberRole
	PodSlug   string
	PodName   string
	SkillSlug string
	SkillName string
}

func (q *Queries) ListPodMembershipsByUserID(ctx context.Context, userID int64) ([]ListPodMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPodMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPodMembershipsByUserIDRow
	for rows.Next() {
		var i ListPodMembershipsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.UserID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.Role,
			&i.PodSlug,
			&i.PodName,
			&i.SkillSlug,
			&i.SkillName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePodMembershipRole = `-- name: UpdatePodMembershipRole :one
UPDATE pod_membership
SET role = $2
WHERE id = $1
RETURNING id, pod_id, user_id, status, joined_at, created_at, role
`

type UpdatePodMembershipRoleParams struct {
	ID   int64
	Role PodMemberRole
}

func (q *Queries) UpdatePodMembershipRole(ctx context.Context, arg UpdatePodMembershipRoleParams) (PodMembership, error) {
	row := q.db.QueryRow(ctx, updatePodMembershipRole, arg.ID, arg.Role)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const updatePodMembershipStatus = `-- name: UpdatePodMembershipStatus :one
UPDATE pod_membership
SET
    status = $2,
    joined_at = $3
WHERE id = $1
RETURNING id, pod_id, user_id, status, joined_at, created_at, role
`

type UpdatePodMembershipStatusParams struct {
	ID       int64
	Status   UserPodMembershipStatus
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePodMembershipStatus(ctx context.Context, arg UpdatePodMembershipStatusParams) (PodMembership, error) {
	row := q.db.QueryRow(ctx, updatePodMembershipStatus, arg.ID, arg.Status, arg.JoinedAt)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const updatePodMembershipStatusAndRole = `-- name: UpdatePodMembershipStatusAndRole :one
UPDATE pod_membership
SET
    status = $2,
    role = $3,
    joined_at = $4
WHERE id = $1
RETURNING id, pod_id, user_id, status, joined_at, created_at, role
`

type UpdatePodMembershipStatusAndRoleParams struct {
	ID       int64
	Status   UserPodMembershipStatus
	Role     PodMemberRole
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePodMembershipStatusAndRole(ctx context.Context, arg UpdatePodMembershipStatusAndRoleParams) (PodMembership, error) {
	row := q.db.QueryRow(ctx, updatePodMembershipStatusAndRole,
		arg.ID,
		arg.Status,
		arg.Role,
		arg.JoinedAt,
	)
	var i PodMembership
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}
