// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelMessage = `-- name: CreateChannelMessage :one

INSERT INTO message (
    author_id,
    community_channel_id,
    pod_id,
    content,
    reply_to_message_id
)
VALUES ($1, $2, NULL, $3, $4)
RETURNING id, author_id, community_channel_id, pod_id, content, edited_at, created_at, reply_to_message_id
`

type CreateChannelMessageParams struct {
	AuthorID           int64
	CommunityChannelID pgtype.Int8
	Content            string
	ReplyToMessageID   pgtype.Int8
}

// =========================================
// MESSAGES
// =========================================
func (q *Queries) CreateChannelMessage(ctx context.Context, arg CreateChannelMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createChannelMessage,
		arg.AuthorID,
		arg.CommunityChannelID,
		arg.Content,
		arg.ReplyToMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CommunityChannelID,
		&i.PodID,
		&i.Content,
		&i.EditedAt,
		&i.CreatedAt,
		&i.ReplyToMessageID,
	)
	return i, err
}

const createPodMessage = `-- name: CreatePodMessage :one
INSERT INTO message (
    author_id,
    community_channel_id,
    pod_id,
    content,
    reply_to_message_id
)
VALUES ($1, NULL, $2, $3, $4)
RETURNING id, author_id, community_channel_id, pod_id, content, edited_at, created_at, reply_to_message_id
`

type CreatePodMessageParams struct {
	AuthorID         int64
	PodID            pgtype.Int8
	Content          string
	ReplyToMessageID pgtype.Int8
}

func (q *Queries) CreatePodMessage(ctx context.Context, arg CreatePodMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createPodMessage,
		arg.AuthorID,
		arg.PodID,
		arg.Content,
		arg.ReplyToMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CommunityChannelID,
		&i.PodID,
		&i.Content,
		&i.EditedAt,
		&i.CreatedAt,
		&i.ReplyToMessageID,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM message
WHERE id = $1
  AND author_id = $2
`

type DeleteMessageParams struct {
	ID       int64
	AuthorID int64
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    m.id,
    m.author_id,
    m.community_channel_id,
    m.pod_id,
    m.content,
    m.edited_at,
    m.created_at,
    m.reply_to_message_id,
    u.username AS author_username,
    u.name AS author_name,
    s.slug AS skill_slug,
    cc.slug AS channel_slug,
    p.slug AS pod_slug,
    parent.content AS reply_to_content,
    parent_author.username AS reply_to_author_username
FROM message m
INNER JOIN users u ON u.id = m.author_id
LEFT JOIN community_channel cc ON cc.id = m.community_channel_id
LEFT JOIN community c ON c.id = cc.community_id
LEFT JOIN skills s ON s.id = c.skill_id
LEFT JOIN pods p ON p.id = m.pod_id
LEFT JOIN message parent ON parent.id = m.reply_to_message_id
LEFT JOIN users parent_author ON parent_author.id = parent.author_id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID                    int64
	AuthorID              int64
	CommunityChannelID    pgtype.Int8
	PodID                 pgtype.Int8
	Content               string
	EditedAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	ReplyToMessageID      pgtype.Int8
	AuthorUsername        string
	AuthorName            string
	SkillSlug             pgtype.Text
	ChannelSlug           pgtype.Text
	PodSlug               pgtype.Text
	ReplyToContent        pgtype.Text
	ReplyToAuthorUsername pgtype.Text
}

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CommunityChannelID,
		&i.PodID,
		&i.Content,
		&i.EditedAt,
		&i.CreatedAt,
		&i.ReplyToMessageID,
		&i.AuthorUsername,
		&i.AuthorName,
		&i.SkillSlug,
		&i.ChannelSlug,
		&i.PodSlug,
		&i.ReplyToContent,
		&i.ReplyToAuthorUsername,
	)
	return i, err
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT
    m.id,
    m.author_id,
    m.community_channel_id,
    m.pod_id,
    m.content,
    m.edited_at,
    m.created_at,
    m.reply_to_message_id,
    u.username AS author_username,
    u.name AS author_name,
    parent.content AS reply_to_content,
    parent_author.username AS reply_to_author_username
FROM message m
INNER JOIN users u ON u.id = m.author_id
LEFT JOIN message parent ON parent.id = m.reply_to_message_id
LEFT JOIN users parent_author ON parent_author.id = parent.author_id
WHERE m.community_channel_id = $1
  AND ($2::bigint = 0 OR m.id < $2)
ORDER BY m.id DESC
LIMIT $3
`

type ListChannelMessagesParams struct {
	ChannelID    pgtype.Int8
	BeforeID     int64
	MessageLimit int32
}

type ListChannelMessagesRow struct {
	ID                    int64
	AuthorID              int64
	CommunityChannelID    pgtype.Int8
	PodID                 pgtype.Int8
	Content               string
	EditedAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	ReplyToMessageID      pgtype.Int8
	AuthorUsername        string
	AuthorName            string
	ReplyToContent        pgtype.Text
	ReplyToAuthorUsername pgtype.Text
}

func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ListChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.BeforeID, arg.MessageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelMessagesRow
	for rows.Next() {
		var i ListChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CommunityChannelID,
			&i.PodID,
			&i.Content,
			&i.EditedAt,
			&i.CreatedAt,
			&i.ReplyToMessageID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.ReplyToContent,
			&i.ReplyToAuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodMessages = `-- name: ListPodMessages :many
SELECT
    m.id,
    m.author_id,
    m.community_channel_id,
    m.pod_id,
    m.content,
    m.edited_at,
    m.created_at,
    m.reply_to_message_id,
    u.username AS author_username,
    u.name AS author_name,
    parent.content AS reply_to_content,
    parent_author.username AS reply_to_author_username
FROM message m
INNER JOIN users u ON u.id = m.author_id
LEFT JOIN message parent ON parent.id = m.reply_to_message_id
LEFT JOIN users parent_author ON parent_author.id = parent.author_id
WHERE m.pod_id = $1
  AND ($2::bigint = 0 OR m.id < $2)
ORDER BY m.id DESC
LIMIT $3
`

type ListPodMessagesParams struct {
	PodID        pgtype.Int8
	BeforeID     int64
	MessageLimit int32
}

type ListPodMessagesRow struct {
	ID                    int64
	AuthorID              int64
	CommunityChannelID    pgtype.Int8
	PodID                 pgtype.Int8
	Content               string
	EditedAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	ReplyToMessageID      pgtype.Int8
	AuthorUsername        string
	AuthorName            string
	ReplyToContent        pgtype.Text
	ReplyToAuthorUsername pgtype.Text
}

func (q *Queries) ListPodMessages(ctx context.Context, arg ListPodMessagesParams) ([]ListPodMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPodMessages, arg.PodID, arg.BeforeID, arg.MessageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPodMessagesRow
	for rows.Next() {
		var i ListPodMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CommunityChannelID,
			&i.PodID,
			&i.Content,
			&i.EditedAt,
			&i.CreatedAt,
			&i.ReplyToMessageID,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.ReplyToContent,
			&i.ReplyToAuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE message
SET
    content = $2,
    edited_at = NOW()
WHERE id = $1
  AND author_id = $3
RETURNING id, author_id, community_channel_id, pod_id, content, edited_at, created_at, reply_to_message_id
`

type UpdateMessageContentParams struct {
	ID       int64
	Content  string
	AuthorID int64
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content, arg.AuthorID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CommunityChannelID,
		&i.PodID,
		&i.Content,
		&i.EditedAt,
		&i.CreatedAt,
		&i.ReplyToMessageID,
	)
	return i, err
}
