// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestone_progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMilestoneProgress = `-- name: CompleteMilestoneProgress :one

UPDATE user_milestone_progress
SET
    status = 'COMPLETED',
    completed_at = NOW(),
    postponed_until = NULL
WHERE id = $1
RETURNING id, user_skill_id, milestone_id, status, completed_at, postponed_until
`

// =========================================
// UPDATE
// =========================================
func (q *Queries) CompleteMilestoneProgress(ctx context.Context, id int64) (UserMilestoneProgress, error) {
	row := q.db.QueryRow(ctx, completeMilestoneProgress, id)
	var i UserMilestoneProgress
	err := row.Scan(
		&i.ID,
		&i.UserSkillID,
		&i.MilestoneID,
		&i.Status,
		&i.CompletedAt,
		&i.PostponedUntil,
	)
	return i, err
}

const countIncompleteChaptersBefore = `-- name: CountIncompleteChaptersBefore :one
SELECT COUNT(*)::bigint
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND m.order_index < $2
  AND m.kind = 'CHAPTER'
  AND ump.status != 'COMPLETED'
`

type CountIncompleteChaptersBeforeParams struct {
	UserSkillID pgtype.Int8
	OrderIndex  int32
}

func (q *Queries) CountIncompleteChaptersBefore(ctx context.Context, arg CountIncompleteChaptersBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteChaptersBefore, arg.UserSkillID, arg.OrderIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countIncompleteMilestonesBefore = `-- name: CountIncompleteMilestonesBefore :one
SELECT COUNT(*)::bigint
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND m.order_index < $2
  AND ump.status != 'COMPLETED'
`

type CountIncompleteMilestonesBeforeParams struct {
	UserSkillID pgtype.Int8
	OrderIndex  int32
}

func (q *Queries) CountIncompleteMilestonesBefore(ctx context.Context, arg CountIncompleteMilestonesBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteMilestonesBefore, arg.UserSkillID, arg.OrderIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countIncompleteTopicMilestonesBefore = `-- name: CountIncompleteTopicMilestonesBefore :one
SELECT COUNT(*)::bigint
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND m.order_index < $2
  AND m.kind = 'TOPIC'
  AND ump.status != 'COMPLETED'
`

type CountIncompleteTopicMilestonesBeforeParams struct {
	UserSkillID pgtype.Int8
	OrderIndex  int32
}

// Subtopics (TOPIC) may be completed without finishing their parent CHAPTER first.
func (q *Queries) CountIncompleteTopicMilestonesBefore(ctx context.Context, arg CountIncompleteTopicMilestonesBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteTopicMilestonesBefore, arg.UserSkillID, arg.OrderIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countIncompleteTopicsInChapter = `-- name: CountIncompleteTopicsInChapter :one
SELECT COUNT(*)::bigint
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND m.kind = 'TOPIC'
  AND m.chapter = $2
  AND ump.status != 'COMPLETED'
`

type CountIncompleteTopicsInChapterParams struct {
	UserSkillID pgtype.Int8
	Chapter     pgtype.Text
}

// Parent CHAPTER cannot complete until every TOPIC in the same chapter is done.
func (q *Queries) CountIncompleteTopicsInChapter(ctx context.Context, arg CountIncompleteTopicsInChapterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteTopicsInChapter, arg.UserSkillID, arg.Chapter)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMilestoneProgress = `-- name: CreateMilestoneProgress :one

INSERT INTO user_milestone_progress (
    user_skill_id,
    milestone_id,
    status
)
VALUES ($1, $2, $3)
RETURNING id, user_skill_id, milestone_id, status, completed_at, postponed_until
`

type CreateMilestoneProgressParams struct {
	UserSkillID pgtype.Int8
	MilestoneID pgtype.Int8
	Status      ProgressStatus
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateMilestoneProgress(ctx context.Context, arg CreateMilestoneProgressParams) (UserMilestoneProgress, error) {
	row := q.db.QueryRow(ctx, createMilestoneProgress, arg.UserSkillID, arg.MilestoneID, arg.Status)
	var i UserMilestoneProgress
	err := row.Scan(
		&i.ID,
		&i.UserSkillID,
		&i.MilestoneID,
		&i.Status,
		&i.CompletedAt,
		&i.PostponedUntil,
	)
	return i, err
}

const deleteMilestoneProgressByUserSkillID = `-- name: DeleteMilestoneProgressByUserSkillID :exec

DELETE FROM user_milestone_progress
WHERE user_skill_id = $1
`

// =========================================
// DELETE
// =========================================
func (q *Queries) DeleteMilestoneProgressByUserSkillID(ctx context.Context, userSkillID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteMilestoneProgressByUserSkillID, userSkillID)
	return err
}

const getMilestoneProgress = `-- name: GetMilestoneProgress :one
SELECT ump.id, ump.user_skill_id, ump.milestone_id, ump.status, ump.completed_at, ump.postponed_until
FROM user_milestone_progress ump
WHERE ump.user_skill_id = $1
  AND ump.milestone_id = $2
`

type GetMilestoneProgressParams struct {
	UserSkillID pgtype.Int8
	MilestoneID pgtype.Int8
}

func (q *Queries) GetMilestoneProgress(ctx context.Context, arg GetMilestoneProgressParams) (UserMilestoneProgress, error) {
	row := q.db.QueryRow(ctx, getMilestoneProgress, arg.UserSkillID, arg.MilestoneID)
	var i UserMilestoneProgress
	err := row.Scan(
		&i.ID,
		&i.UserSkillID,
		&i.MilestoneID,
		&i.Status,
		&i.CompletedAt,
		&i.PostponedUntil,
	)
	return i, err
}

const getMilestoneProgressBySlug = `-- name: GetMilestoneProgressBySlug :one
SELECT ump.id, ump.user_skill_id, ump.milestone_id, ump.status, ump.completed_at, ump.postponed_until,
       m.title, m.slug, m.description, m.estimated_hours, m.order_index, m.difficulty, m.chapter, m.kind
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND m.slug = $2
`

type GetMilestoneProgressBySlugParams struct {
	UserSkillID pgtype.Int8
	Slug        string
}

type GetMilestoneProgressBySlugRow struct {
	ID             int64
	UserSkillID    pgtype.Int8
	MilestoneID    pgtype.Int8
	Status         ProgressStatus
	CompletedAt    pgtype.Timestamptz
	PostponedUntil pgtype.Timestamptz
	Title          string
	Slug           string
	Description    pgtype.Text
	EstimatedHours pgtype.Int4
	OrderIndex     int32
	Difficulty     pgtype.Text
	Chapter        pgtype.Text
	Kind           string
}

func (q *Queries) GetMilestoneProgressBySlug(ctx context.Context, arg GetMilestoneProgressBySlugParams) (GetMilestoneProgressBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMilestoneProgressBySlug, arg.UserSkillID, arg.Slug)
	var i GetMilestoneProgressBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserSkillID,
		&i.MilestoneID,
		&i.Status,
		&i.CompletedAt,
		&i.PostponedUntil,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.EstimatedHours,
		&i.OrderIndex,
		&i.Difficulty,
		&i.Chapter,
		&i.Kind,
	)
	return i, err
}

const listCompletedMilestoneSlugsByUserSkillID = `-- name: ListCompletedMilestoneSlugsByUserSkillID :many
SELECT m.slug
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
  AND ump.status = 'COMPLETED'
`

func (q *Queries) ListCompletedMilestoneSlugsByUserSkillID(ctx context.Context, userSkillID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listCompletedMilestoneSlugsByUserSkillID, userSkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestoneProgressByUserSkillID = `-- name: ListMilestoneProgressByUserSkillID :many

SELECT ump.id, ump.user_skill_id, ump.milestone_id, ump.status, ump.completed_at, ump.postponed_until,
       m.title, m.slug, m.description, m.estimated_hours, m.order_index, m.difficulty, m.chapter, m.kind
FROM user_milestone_progress ump
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE ump.user_skill_id = $1
ORDER BY m.order_index
`

type ListMilestoneProgressByUserSkillIDRow struct {
	ID             int64
	UserSkillID    pgtype.Int8
	MilestoneID    pgtype.Int8
	Status         ProgressStatus
	CompletedAt    pgtype.Timestamptz
	PostponedUntil pgtype.Timestamptz
	Title          string
	Slug           string
	Description    pgtype.Text
	EstimatedHours pgtype.Int4
	OrderIndex     int32
	Difficulty     pgtype.Text
	Chapter        pgtype.Text
	Kind           string
}

// =========================================
// GET
// =========================================
func (q *Queries) ListMilestoneProgressByUserSkillID(ctx context.Context, userSkillID pgtype.Int8) ([]ListMilestoneProgressByUserSkillIDRow, error) {
	rows, err := q.db.Query(ctx, listMilestoneProgressByUserSkillID, userSkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMilestoneProgressByUserSkillIDRow
	for rows.Next() {
		var i ListMilestoneProgressByUserSkillIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserSkillID,
			&i.MilestoneID,
			&i.Status,
			&i.CompletedAt,
			&i.PostponedUntil,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.EstimatedHours,
			&i.OrderIndex,
			&i.Difficulty,
			&i.Chapter,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postponeMilestoneProgress = `-- name: PostponeMilestoneProgress :one
UPDATE user_milestone_progress
SET
    status = 'POSTPONED',
    postponed_until = $2,
    completed_at = NULL
WHERE id = $1
RETURNING id, user_skill_id, milestone_id, status, completed_at, postponed_until
`

type PostponeMilestoneProgressParams struct {
	ID             int64
	PostponedUntil pgtype.Timestamptz
}

func (q *Queries) PostponeMilestoneProgress(ctx context.Context, arg PostponeMilestoneProgressParams) (UserMilestoneProgress, error) {
	row := q.db.QueryRow(ctx, postponeMilestoneProgress, arg.ID, arg.PostponedUntil)
	var i UserMilestoneProgress
	err := row.Scan(
		&i.ID,
		&i.UserSkillID,
		&i.MilestoneID,
		&i.Status,
		&i.CompletedAt,
		&i.PostponedUntil,
	)
	return i, err
}
