// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMilestoneByID = `-- name: GetMilestoneByID :one
SELECT id, roadmap_version_id, title, slug, description, estimated_hours, order_index, difficulty, chapter, kind, created_at, updated_at
FROM milestones
WHERE id = $1
`

type GetMilestoneByIDRow struct {
	ID               int64
	RoadmapVersionID pgtype.Int8
	Title            string
	Slug             string
	Description      pgtype.Text
	EstimatedHours   pgtype.Int4
	OrderIndex       int32
	Difficulty       pgtype.Text
	Chapter          pgtype.Text
	Kind             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMilestoneByID(ctx context.Context, id int64) (GetMilestoneByIDRow, error) {
	row := q.db.QueryRow(ctx, getMilestoneByID, id)
	var i GetMilestoneByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoadmapVersionID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.EstimatedHours,
		&i.OrderIndex,
		&i.Difficulty,
		&i.Chapter,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMilestoneBySlugAndRoadmapVersion = `-- name: GetMilestoneBySlugAndRoadmapVersion :one
SELECT id, roadmap_version_id, title, slug, description, estimated_hours, order_index, difficulty, chapter, kind, created_at, updated_at
FROM milestones
WHERE roadmap_version_id = $1
  AND slug = $2
`

type GetMilestoneBySlugAndRoadmapVersionParams struct {
	RoadmapVersionID pgtype.Int8
	Slug             string
}

type GetMilestoneBySlugAndRoadmapVersionRow struct {
	ID               int64
	RoadmapVersionID pgtype.Int8
	Title            string
	Slug             string
	Description      pgtype.Text
	EstimatedHours   pgtype.Int4
	OrderIndex       int32
	Difficulty       pgtype.Text
	Chapter          pgtype.Text
	Kind             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMilestoneBySlugAndRoadmapVersion(ctx context.Context, arg GetMilestoneBySlugAndRoadmapVersionParams) (GetMilestoneBySlugAndRoadmapVersionRow, error) {
	row := q.db.QueryRow(ctx, getMilestoneBySlugAndRoadmapVersion, arg.RoadmapVersionID, arg.Slug)
	var i GetMilestoneBySlugAndRoadmapVersionRow
	err := row.Scan(
		&i.ID,
		&i.RoadmapVersionID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.EstimatedHours,
		&i.OrderIndex,
		&i.Difficulty,
		&i.Chapter,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMilestonesByRoadmapVersionID = `-- name: ListMilestonesByRoadmapVersionID :many

SELECT id, roadmap_version_id, title, slug, description, estimated_hours, order_index, difficulty, chapter, kind, created_at, updated_at
FROM milestones
WHERE roadmap_version_id = $1
ORDER BY order_index
`

type ListMilestonesByRoadmapVersionIDRow struct {
	ID               int64
	RoadmapVersionID pgtype.Int8
	Title            string
	Slug             string
	Description      pgtype.Text
	EstimatedHours   pgtype.Int4
	OrderIndex       int32
	Difficulty       pgtype.Text
	Chapter          pgtype.Text
	Kind             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// =========================================
// GET
// =========================================
func (q *Queries) ListMilestonesByRoadmapVersionID(ctx context.Context, roadmapVersionID pgtype.Int8) ([]ListMilestonesByRoadmapVersionIDRow, error) {
	rows, err := q.db.Query(ctx, listMilestonesByRoadmapVersionID, roadmapVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMilestonesByRoadmapVersionIDRow
	for rows.Next() {
		var i ListMilestonesByRoadmapVersionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapVersionID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.EstimatedHours,
			&i.OrderIndex,
			&i.Difficulty,
			&i.Chapter,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
