// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AudioRoomParticipantRole string

const (
	AudioRoomParticipantRoleHOST     AudioRoomParticipantRole = "HOST"
	AudioRoomParticipantRoleSPEAKER  AudioRoomParticipantRole = "SPEAKER"
	AudioRoomParticipantRoleLISTENER AudioRoomParticipantRole = "LISTENER"
)

func (e *AudioRoomParticipantRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioRoomParticipantRole(s)
	case string:
		*e = AudioRoomParticipantRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioRoomParticipantRole: %T", src)
	}
	return nil
}

type NullAudioRoomParticipantRole struct {
	AudioRoomParticipantRole AudioRoomParticipantRole
	Valid                    bool // Valid is true if AudioRoomParticipantRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioRoomParticipantRole) Scan(value interface{}) error {
	if value == nil {
		ns.AudioRoomParticipantRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioRoomParticipantRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioRoomParticipantRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioRoomParticipantRole), nil
}

type AudioRoomStatus string

const (
	AudioRoomStatusSCHEDULED AudioRoomStatus = "SCHEDULED"
	AudioRoomStatusACTIVE    AudioRoomStatus = "ACTIVE"
	AudioRoomStatusENDED     AudioRoomStatus = "ENDED"
	AudioRoomStatusCANCELLED AudioRoomStatus = "CANCELLED"
)

func (e *AudioRoomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioRoomStatus(s)
	case string:
		*e = AudioRoomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioRoomStatus: %T", src)
	}
	return nil
}

type NullAudioRoomStatus struct {
	AudioRoomStatus AudioRoomStatus
	Valid           bool // Valid is true if AudioRoomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioRoomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AudioRoomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioRoomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioRoomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioRoomStatus), nil
}

type AudioRoomType string

const (
	AudioRoomTypePOD              AudioRoomType = "POD"
	AudioRoomTypeCOMMUNITYCHANNEL AudioRoomType = "COMMUNITY_CHANNEL"
)

func (e *AudioRoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioRoomType(s)
	case string:
		*e = AudioRoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioRoomType: %T", src)
	}
	return nil
}

type NullAudioRoomType struct {
	AudioRoomType AudioRoomType
	Valid         bool // Valid is true if AudioRoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.AudioRoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioRoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioRoomType), nil
}

type CatalogRequestStatus string

const (
	CatalogRequestStatusPENDING    CatalogRequestStatus = "PENDING"
	CatalogRequestStatusAPPROVED   CatalogRequestStatus = "APPROVED"
	CatalogRequestStatusREJECTED   CatalogRequestStatus = "REJECTED"
	CatalogRequestStatusCANCELLED  CatalogRequestStatus = "CANCELLED"
	CatalogRequestStatusGENERATING CatalogRequestStatus = "GENERATING"
	CatalogRequestStatusFAILED     CatalogRequestStatus = "FAILED"
)

func (e *CatalogRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogRequestStatus(s)
	case string:
		*e = CatalogRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogRequestStatus: %T", src)
	}
	return nil
}

type NullCatalogRequestStatus struct {
	CatalogRequestStatus CatalogRequestStatus
	Valid                bool // Valid is true if CatalogRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogRequestStatus), nil
}

type CurrentStatus string

const (
	CurrentStatusDRAFT    CurrentStatus = "DRAFT"
	CurrentStatusACTIVE   CurrentStatus = "ACTIVE"
	CurrentStatusARCHIVED CurrentStatus = "ARCHIVED"
)

func (e *CurrentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrentStatus(s)
	case string:
		*e = CurrentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrentStatus: %T", src)
	}
	return nil
}

type NullCurrentStatus struct {
	CurrentStatus CurrentStatus
	Valid         bool // Valid is true if CurrentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CurrentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrentStatus), nil
}

type MilestoneProposalStatus string

const (
	MilestoneProposalStatusPENDING     MilestoneProposalStatus = "PENDING"
	MilestoneProposalStatusAPPROVED    MilestoneProposalStatus = "APPROVED"
	MilestoneProposalStatusREJECTED    MilestoneProposalStatus = "REJECTED"
	MilestoneProposalStatusIMPLEMENTED MilestoneProposalStatus = "IMPLEMENTED"
)

func (e *MilestoneProposalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MilestoneProposalStatus(s)
	case string:
		*e = MilestoneProposalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MilestoneProposalStatus: %T", src)
	}
	return nil
}

type NullMilestoneProposalStatus struct {
	MilestoneProposalStatus MilestoneProposalStatus
	Valid                   bool // Valid is true if MilestoneProposalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMilestoneProposalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MilestoneProposalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MilestoneProposalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMilestoneProposalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MilestoneProposalStatus), nil
}

type MilestoneProposalType string

const (
	MilestoneProposalTypeADD     MilestoneProposalType = "ADD"
	MilestoneProposalTypeREMOVE  MilestoneProposalType = "REMOVE"
	MilestoneProposalTypeEDIT    MilestoneProposalType = "EDIT"
	MilestoneProposalTypeREORDER MilestoneProposalType = "REORDER"
	MilestoneProposalTypeMERGE   MilestoneProposalType = "MERGE"
	MilestoneProposalTypeSPLIT   MilestoneProposalType = "SPLIT"
)

func (e *MilestoneProposalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MilestoneProposalType(s)
	case string:
		*e = MilestoneProposalType(s)
	default:
		return fmt.Errorf("unsupported scan type for MilestoneProposalType: %T", src)
	}
	return nil
}

type NullMilestoneProposalType struct {
	MilestoneProposalType MilestoneProposalType
	Valid                 bool // Valid is true if MilestoneProposalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMilestoneProposalType) Scan(value interface{}) error {
	if value == nil {
		ns.MilestoneProposalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MilestoneProposalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMilestoneProposalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MilestoneProposalType), nil
}

type NotificationType string

const (
	NotificationTypePODJOINREQUEST         NotificationType = "POD_JOIN_REQUEST"
	NotificationTypePODJOINACCEPTED        NotificationType = "POD_JOIN_ACCEPTED"
	NotificationTypePODJOINREJECTED        NotificationType = "POD_JOIN_REJECTED"
	NotificationTypePODMEMBERREMOVED       NotificationType = "POD_MEMBER_REMOVED"
	NotificationTypeMILESTONEDUE           NotificationType = "MILESTONE_DUE"
	NotificationTypeMILESTONECOMPLETED     NotificationType = "MILESTONE_COMPLETED"
	NotificationTypeROADMAPUPDATED         NotificationType = "ROADMAP_UPDATED"
	NotificationTypePROPOSALAPPROVED       NotificationType = "PROPOSAL_APPROVED"
	NotificationTypePROPOSALREJECTED       NotificationType = "PROPOSAL_REJECTED"
	NotificationTypeCOMMUNITYANNOUNCEMENT  NotificationType = "COMMUNITY_ANNOUNCEMENT"
	NotificationTypeSYSTEM                 NotificationType = "SYSTEM"
	NotificationTypeSKILLREQUESTAPPROVED   NotificationType = "SKILL_REQUEST_APPROVED"
	NotificationTypeSKILLREQUESTREJECTED   NotificationType = "SKILL_REQUEST_REJECTED"
	NotificationTypeROADMAPREQUESTAPPROVED NotificationType = "ROADMAP_REQUEST_APPROVED"
	NotificationTypeROADMAPREQUESTREJECTED NotificationType = "ROADMAP_REQUEST_REJECTED"
	NotificationTypeSKILLREQUESTREADY      NotificationType = "SKILL_REQUEST_READY"
	NotificationTypeSKILLREQUESTFAILED     NotificationType = "SKILL_REQUEST_FAILED"
	NotificationTypeROADMAPREQUESTREADY    NotificationType = "ROADMAP_REQUEST_READY"
	NotificationTypeROADMAPREQUESTFAILED   NotificationType = "ROADMAP_REQUEST_FAILED"
	NotificationTypeQUIZREADY              NotificationType = "QUIZ_READY"
	NotificationTypeQUIZFAILED             NotificationType = "QUIZ_FAILED"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PaymentStatus string

const (
	PaymentStatusCREATED PaymentStatus = "CREATED"
	PaymentStatusPAID    PaymentStatus = "PAID"
	PaymentStatusFAILED  PaymentStatus = "FAILED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PodMemberRole string

const (
	PodMemberRoleOWNER  PodMemberRole = "OWNER"
	PodMemberRoleADMIN  PodMemberRole = "ADMIN"
	PodMemberRoleMEMBER PodMemberRole = "MEMBER"
)

func (e *PodMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PodMemberRole(s)
	case string:
		*e = PodMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PodMemberRole: %T", src)
	}
	return nil
}

type NullPodMemberRole struct {
	PodMemberRole PodMemberRole
	Valid         bool // Valid is true if PodMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPodMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.PodMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PodMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPodMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PodMemberRole), nil
}

type PodQuizStatus string

const (
	PodQuizStatusINPROGRESS PodQuizStatus = "IN_PROGRESS"
	PodQuizStatusCOMPLETED  PodQuizStatus = "COMPLETED"
	PodQuizStatusABANDONED  PodQuizStatus = "ABANDONED"
	PodQuizStatusGENERATING PodQuizStatus = "GENERATING"
	PodQuizStatusFAILED     PodQuizStatus = "FAILED"
)

func (e *PodQuizStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PodQuizStatus(s)
	case string:
		*e = PodQuizStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PodQuizStatus: %T", src)
	}
	return nil
}

type NullPodQuizStatus struct {
	PodQuizStatus PodQuizStatus
	Valid         bool // Valid is true if PodQuizStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPodQuizStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PodQuizStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PodQuizStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPodQuizStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PodQuizStatus), nil
}

type ProgressStatus string

const (
	ProgressStatusNOTSTARTED ProgressStatus = "NOT_STARTED"
	ProgressStatusINPROGRESS ProgressStatus = "IN_PROGRESS"
	ProgressStatusCOMPLETED  ProgressStatus = "COMPLETED"
	ProgressStatusPOSTPONED  ProgressStatus = "POSTPONED"
)

func (e *ProgressStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressStatus(s)
	case string:
		*e = ProgressStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressStatus: %T", src)
	}
	return nil
}

type NullProgressStatus struct {
	ProgressStatus ProgressStatus
	Valid          bool // Valid is true if ProgressStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressStatus), nil
}

type ProposalVoteType string

const (
	ProposalVoteTypeUPVOTE   ProposalVoteType = "UPVOTE"
	ProposalVoteTypeDOWNVOTE ProposalVoteType = "DOWNVOTE"
)

func (e *ProposalVoteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalVoteType(s)
	case string:
		*e = ProposalVoteType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalVoteType: %T", src)
	}
	return nil
}

type NullProposalVoteType struct {
	ProposalVoteType ProposalVoteType
	Valid            bool // Valid is true if ProposalVoteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalVoteType) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalVoteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalVoteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalVoteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalVoteType), nil
}

type ProviderName string

const (
	ProviderNameLocal  ProviderName = "local"
	ProviderNameGoogle ProviderName = "google"
)

func (e *ProviderName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderName(s)
	case string:
		*e = ProviderName(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderName: %T", src)
	}
	return nil
}

type NullProviderName struct {
	ProviderName ProviderName
	Valid        bool // Valid is true if ProviderName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderName) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderName), nil
}

type ReportStatus string

const (
	ReportStatusOPEN        ReportStatus = "OPEN"
	ReportStatusUNDERREVIEW ReportStatus = "UNDER_REVIEW"
	ReportStatusRESOLVED    ReportStatus = "RESOLVED"
	ReportStatusDISMISSED   ReportStatus = "DISMISSED"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ReportTargetType string

const (
	ReportTargetTypeUSER             ReportTargetType = "USER"
	ReportTargetTypePROPOSAL         ReportTargetType = "PROPOSAL"
	ReportTargetTypePOD              ReportTargetType = "POD"
	ReportTargetTypeMESSAGE          ReportTargetType = "MESSAGE"
	ReportTargetTypeAUDIOROOM        ReportTargetType = "AUDIO_ROOM"
	ReportTargetTypeCOMMUNITYCHANNEL ReportTargetType = "COMMUNITY_CHANNEL"
)

func (e *ReportTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportTargetType(s)
	case string:
		*e = ReportTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportTargetType: %T", src)
	}
	return nil
}

type NullReportTargetType struct {
	ReportTargetType ReportTargetType
	Valid            bool // Valid is true if ReportTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportTargetType), nil
}

type StatusValue string

const (
	StatusValueACTIVE    StatusValue = "ACTIVE"
	StatusValueCOMPLETED StatusValue = "COMPLETED"
)

func (e *StatusValue) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusValue(s)
	case string:
		*e = StatusValue(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusValue: %T", src)
	}
	return nil
}

type NullStatusValue struct {
	StatusValue StatusValue
	Valid       bool // Valid is true if StatusValue is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusValue) Scan(value interface{}) error {
	if value == nil {
		ns.StatusValue, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusValue.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusValue) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusValue), nil
}

type SubscriptionTier string

const (
	SubscriptionTierFREE    SubscriptionTier = "FREE"
	SubscriptionTierPREMIUM SubscriptionTier = "PREMIUM"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier
	Valid            bool // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

type UserPodMembershipStatus string

const (
	UserPodMembershipStatusPENDING  UserPodMembershipStatus = "PENDING"
	UserPodMembershipStatusACCEPTED UserPodMembershipStatus = "ACCEPTED"
	UserPodMembershipStatusREJECTED UserPodMembershipStatus = "REJECTED"
	UserPodMembershipStatusLEFT     UserPodMembershipStatus = "LEFT"
	UserPodMembershipStatusREMOVED  UserPodMembershipStatus = "REMOVED"
)

func (e *UserPodMembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPodMembershipStatus(s)
	case string:
		*e = UserPodMembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPodMembershipStatus: %T", src)
	}
	return nil
}

type NullUserPodMembershipStatus struct {
	UserPodMembershipStatus UserPodMembershipStatus
	Valid                   bool // Valid is true if UserPodMembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPodMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserPodMembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPodMembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPodMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPodMembershipStatus), nil
}

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AudioRoom struct {
	ID                 int64
	PublicID           uuid.UUID
	RoomType           AudioRoomType
	PodID              pgtype.Int8
	CommunityChannelID pgtype.Int8
	HostID             int64
	Title              string
	Description        pgtype.Text
	LivekitRoomName    string
	Status             AudioRoomStatus
	ScheduledStartTime pgtype.Timestamptz
	ActualStartTime    pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	MaxParticipants    pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AudioRoomParticipant struct {
	ID              int64
	AudioRoomID     int64
	UserID          int64
	JoinedAt        pgtype.Timestamptz
	LeftAt          pgtype.Timestamptz
	DurationSeconds pgtype.Int4
	Role            AudioRoomParticipantRole
}

type Community struct {
	ID          int64
	SkillID     int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CommunityChannel struct {
	ID          int64
	CommunityID int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Slug        string
}

type EmailVerificationOtp struct {
	ID         int64
	UserID     int64
	OtpHash    string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Message struct {
	ID                 int64
	AuthorID           int64
	CommunityChannelID pgtype.Int8
	PodID              pgtype.Int8
	Content            string
	EditedAt           pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ReplyToMessageID   pgtype.Int8
}

type Milestone struct {
	ID               int64
	RoadmapVersionID pgtype.Int8
	Title            string
	Description      pgtype.Text
	EstimatedHours   pgtype.Int4
	OrderIndex       int32
	Difficulty       pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Slug             string
	// Curriculum chapter/section title for grouping topic milestones
	Chapter pgtype.Text
	// CHAPTER = section overview; TOPIC = concrete learning unit
	Kind string
}

type MilestoneProposal struct {
	ID               int64
	RoadmapVersionID int64
	ProposerID       int64
	ProposalType     MilestoneProposalType
	Title            string
	Description      pgtype.Text
	Status           MilestoneProposalStatus
	ReviewedAt       pgtype.Timestamptz
	ReviewedBy       pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Notification struct {
	ID         int64
	UserID     int64
	Type       NotificationType
	EntityType pgtype.Text
	EntityID   pgtype.Int8
	Title      string
	Body       string
	IsRead     bool
	ReadAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Payment struct {
	ID                int64
	PublicID          uuid.UUID
	UserID            int64
	RazorpayOrderID   string
	RazorpayPaymentID pgtype.Text
	Amount            int32
	Currency          string
	Status            PaymentStatus
	Receipt           string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Pod struct {
	ID          int64
	PublicID    uuid.UUID
	Slug        string
	Name        string
	Description pgtype.Text
	OwnerID     int64
	SkillID     int64
	MaxMembers  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PodMembership struct {
	ID        int64
	PodID     int64
	UserID    int64
	Status    UserPodMembershipStatus
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Role      PodMemberRole
}

type PodQuiz struct {
	ID                   int64
	PublicID             uuid.UUID
	PodID                int64
	UserID               int64
	SkillID              int64
	Status               PodQuizStatus
	TopicCount           int32
	CorrectCount         int32
	Score                int32
	CompletedTopicTitles []byte
	CreatedAt            pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
}

type PodQuizAnswer struct {
	ID              int64
	QuizID          int64
	QuestionID      int64
	SelectedIndices []byte
	IsCorrect       bool
	StartedAt       pgtype.Timestamptz
	AnsweredAt      pgtype.Timestamptz
	TimedOut        bool
}

type PodQuizQuestion struct {
	ID             int64
	QuizID         int64
	OrderIndex     int32
	Difficulty     int32
	Prompt         string
	Options        []byte
	CorrectIndices []byte
	TopicTitle     string
	Weight         int32
}

type ProposalVote struct {
	ID         int64
	ProposalID int64
	UserID     int64
	VoteType   ProposalVoteType
	CreatedAt  pgtype.Timestamptz
}

type Report struct {
	ID         int64
	ReporterID int64
	TargetType ReportTargetType
	TargetID   int64
	Reason     string
	Status     ReportStatus
	ResolvedAt pgtype.Timestamptz
	ResolvedBy pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Roadmap struct {
	ID               int64
	CurrentVersionID pgtype.Int8
	SkillID          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RoadmapEditRequest struct {
	ID                int64
	PublicID          uuid.UUID
	SkillID           int64
	RequesterID       int64
	Rationale         pgtype.Text
	Status            CatalogRequestStatus
	BaseVersionNumber int32
	DraftMilestones   []byte
	AdminNote         pgtype.Text
	ReviewedBy        pgtype.Int8
	ReviewedAt        pgtype.Timestamptz
	CreatedVersionID  pgtype.Int8
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RoadmapVersion struct {
	ID            int64
	RoadmapID     pgtype.Int8
	VersionNumber int32
	Status        CurrentStatus
	GeneratedBy   string
	PublishedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Skill struct {
	ID          int64
	Name        string
	Slug        string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SkillCreationRequest struct {
	ID              int64
	PublicID        uuid.UUID
	RequesterID     int64
	Name            string
	SlugCandidate   string
	Description     pgtype.Text
	Status          CatalogRequestStatus
	SimilarSkills   []byte
	DraftMilestones []byte
	AdminNote       pgtype.Text
	ReviewedBy      pgtype.Int8
	ReviewedAt      pgtype.Timestamptz
	CreatedSkillID  pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Streak struct {
	ID               int64
	UserID           pgtype.Int8
	CurrentStreak    int32
	LongestStreak    int32
	LastActivityDate pgtype.Date
	FreezeCount      int32
	UpdatedAt        pgtype.Timestamptz
}

type StudySession struct {
	ID              int64
	UserID          pgtype.Int8
	SkillID         pgtype.Int8
	DurationMinutes int32
	Notes           pgtype.Text
	StudiedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID                int64
	PublicID          uuid.UUID
	Email             string
	Username          string
	Name              string
	ProfilePictureUrl pgtype.Text
	Bio               pgtype.Text
	Subscription      SubscriptionTier
	EmailVerified     bool
	IsDeleted         bool
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	// Platform role: USER or ADMIN. ADMIN is bootstrapped from ADMIN_USERNAMES.
	Role UserRole
}

type UserIdentity struct {
	ID             int64
	UserID         int64
	Provider       ProviderName
	ProviderUserID pgtype.Text
	PasswordHash   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserMilestoneProgress struct {
	ID             int64
	UserSkillID    pgtype.Int8
	MilestoneID    pgtype.Int8
	Status         ProgressStatus
	CompletedAt    pgtype.Timestamptz
	PostponedUntil pgtype.Timestamptz
}

type UserSession struct {
	ID               int64
	PublicID         uuid.UUID
	UserID           int64
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        *netip.Addr
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type UsernameHistory struct {
	ID        int64
	UserID    int64
	Username  string
	CreatedAt pgtype.Timestamptz
}

type Userskill struct {
	ID               int64
	UserID           int64
	SkillID          int64
	RoadmapVersionID int64
	Status           StatusValue
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}
