// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint
FROM notification
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notification (
    user_id,
    type,
    entity_type,
    entity_id,
    title,
    body
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, entity_type, entity_id, title, body, is_read, read_at, created_at
`

type CreateNotificationParams struct {
	UserID     int64
	Type       NotificationType
	EntityType pgtype.Text
	EntityID   pgtype.Int8
	Title      string
	Body       string
}

// =========================================
// NOTIFICATIONS
// =========================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.EntityType,
		arg.EntityID,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Body,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReadNotificationsByUserID = `-- name: DeleteReadNotificationsByUserID :execrows
DELETE FROM notification
WHERE user_id = $1
  AND is_read = TRUE
`

func (q *Queries) DeleteReadNotificationsByUserID(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReadNotificationsByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByIDAndUserID = `-- name: GetNotificationByIDAndUserID :one
SELECT id, user_id, type, entity_type, entity_id, title, body, is_read, read_at, created_at
FROM notification
WHERE id = $1
  AND user_id = $2
`

type GetNotificationByIDAndUserIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetNotificationByIDAndUserID(ctx context.Context, arg GetNotificationByIDAndUserIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByIDAndUserID, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Body,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, type, entity_type, entity_id, title, body, is_read, read_at, created_at
FROM notification
WHERE user_id = $1
  AND ($2::boolean = FALSE OR is_read = FALSE)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotificationsByUserIDParams struct {
	UserID     int64
	UnreadOnly bool
	NotifLimit int32
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.UnreadOnly, arg.NotifLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Title,
			&i.Body,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notification
SET
    is_read = TRUE,
    read_at = NOW()
WHERE user_id = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notification
SET
    is_read = TRUE,
    read_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND is_read = FALSE
RETURNING id, user_id, type, entity_type, entity_id, title, body, is_read, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Body,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
