// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAudioRoomParticipant = `-- name: GetAudioRoomParticipant :one
SELECT id, audio_room_id, user_id, joined_at, left_at, duration_seconds, role
FROM audio_room_participant
WHERE audio_room_id = $1
  AND user_id = $2
`

type GetAudioRoomParticipantParams struct {
	AudioRoomID int64
	UserID      int64
}

func (q *Queries) GetAudioRoomParticipant(ctx context.Context, arg GetAudioRoomParticipantParams) (AudioRoomParticipant, error) {
	row := q.db.QueryRow(ctx, getAudioRoomParticipant, arg.AudioRoomID, arg.UserID)
	var i AudioRoomParticipant
	err := row.Scan(
		&i.ID,
		&i.AudioRoomID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
		&i.Role,
	)
	return i, err
}

const leaveAllActiveAudioParticipants = `-- name: LeaveAllActiveAudioParticipants :execrows
UPDATE audio_room_participant
SET
    left_at = NOW(),
    duration_seconds = GREATEST(
        0,
        EXTRACT(EPOCH FROM (NOW() - joined_at))::integer
    )
WHERE left_at IS NULL
`

func (q *Queries) LeaveAllActiveAudioParticipants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, leaveAllActiveAudioParticipants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaveAudioRoomParticipant = `-- name: LeaveAudioRoomParticipant :one
UPDATE audio_room_participant
SET
    left_at = NOW(),
    duration_seconds = GREATEST(
        0,
        EXTRACT(EPOCH FROM (NOW() - joined_at))::integer
    )
WHERE audio_room_id = $1
  AND user_id = $2
  AND left_at IS NULL
RETURNING id, audio_room_id, user_id, joined_at, left_at, duration_seconds, role
`

type LeaveAudioRoomParticipantParams struct {
	AudioRoomID int64
	UserID      int64
}

func (q *Queries) LeaveAudioRoomParticipant(ctx context.Context, arg LeaveAudioRoomParticipantParams) (AudioRoomParticipant, error) {
	row := q.db.QueryRow(ctx, leaveAudioRoomParticipant, arg.AudioRoomID, arg.UserID)
	var i AudioRoomParticipant
	err := row.Scan(
		&i.ID,
		&i.AudioRoomID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
		&i.Role,
	)
	return i, err
}

const listActiveAudioRoomParticipants = `-- name: ListActiveAudioRoomParticipants :many
SELECT
    arp.id,
    arp.audio_room_id,
    arp.user_id,
    arp.joined_at,
    arp.left_at,
    arp.duration_seconds,
    arp.role,
    u.username,
    u.name AS user_name
FROM audio_room_participant arp
INNER JOIN users u ON u.id = arp.user_id
WHERE arp.audio_room_id = $1
  AND arp.left_at IS NULL
ORDER BY
    CASE arp.role
        WHEN 'HOST' THEN 0
        WHEN 'SPEAKER' THEN 1
        ELSE 2
    END,
    arp.joined_at ASC
`

type ListActiveAudioRoomParticipantsRow struct {
	ID              int64
	AudioRoomID     int64
	UserID          int64
	JoinedAt        pgtype.Timestamptz
	LeftAt          pgtype.Timestamptz
	DurationSeconds pgtype.Int4
	Role            AudioRoomParticipantRole
	Username        string
	UserName        string
}

func (q *Queries) ListActiveAudioRoomParticipants(ctx context.Context, audioRoomID int64) ([]ListActiveAudioRoomParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAudioRoomParticipants, audioRoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAudioRoomParticipantsRow
	for rows.Next() {
		var i ListActiveAudioRoomParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.AudioRoomID,
			&i.UserID,
			&i.JoinedAt,
			&i.LeftAt,
			&i.DurationSeconds,
			&i.Role,
			&i.Username,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAudioRoomParticipant = `-- name: UpsertAudioRoomParticipant :one

INSERT INTO audio_room_participant (
    audio_room_id,
    user_id,
    joined_at,
    left_at,
    duration_seconds,
    role
)
VALUES ($1, $2, $3, NULL, NULL, $4)
ON CONFLICT (audio_room_id, user_id) DO UPDATE
SET
    joined_at = EXCLUDED.joined_at,
    left_at = NULL,
    duration_seconds = NULL,
    role = CASE
        WHEN audio_room_participant.role = 'HOST' THEN audio_room_participant.role
        ELSE EXCLUDED.role
    END
RETURNING id, audio_room_id, user_id, joined_at, left_at, duration_seconds, role
`

type UpsertAudioRoomParticipantParams struct {
	AudioRoomID int64
	UserID      int64
	JoinedAt    pgtype.Timestamptz
	Role        AudioRoomParticipantRole
}

// =========================================
// AUDIO ROOM PARTICIPANTS
// =========================================
func (q *Queries) UpsertAudioRoomParticipant(ctx context.Context, arg UpsertAudioRoomParticipantParams) (AudioRoomParticipant, error) {
	row := q.db.QueryRow(ctx, upsertAudioRoomParticipant,
		arg.AudioRoomID,
		arg.UserID,
		arg.JoinedAt,
		arg.Role,
	)
	var i AudioRoomParticipant
	err := row.Scan(
		&i.ID,
		&i.AudioRoomID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
		&i.Role,
	)
	return i, err
}
