// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    user_id,
    razorpay_order_id,
    amount,
    currency,
    status,
    receipt
) VALUES (
    $1, $2, $3, $4, 'CREATED', $5
)
RETURNING id, public_id, user_id, razorpay_order_id, razorpay_payment_id, amount, currency, status, receipt, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID          int64
	RazorpayOrderID string
	Amount          int32
	Currency        string
	Receipt         string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.RazorpayOrderID,
		arg.Amount,
		arg.Currency,
		arg.Receipt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Receipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, public_id, user_id, razorpay_order_id, razorpay_payment_id, amount, currency, status, receipt, created_at, updated_at FROM payments
WHERE razorpay_order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, razorpayOrderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, razorpayOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Receipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentID = `-- name: GetPaymentByPaymentID :one
SELECT id, public_id, user_id, razorpay_order_id, razorpay_payment_id, amount, currency, status, receipt, created_at, updated_at FROM payments
WHERE razorpay_payment_id = $1
`

func (q *Queries) GetPaymentByPaymentID(ctx context.Context, razorpayPaymentID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentID, razorpayPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Receipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET
    status = 'PAID',
    razorpay_payment_id = $2,
    updated_at = NOW()
WHERE razorpay_order_id = $1
  AND status = 'CREATED'
RETURNING id, public_id, user_id, razorpay_order_id, razorpay_payment_id, amount, currency, status, receipt, created_at, updated_at
`

type MarkPaymentPaidParams struct {
	RazorpayOrderID   string
	RazorpayPaymentID pgtype.Text
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, arg.RazorpayOrderID, arg.RazorpayPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Receipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentPaidIdempotent = `-- name: MarkPaymentPaidIdempotent :one
UPDATE payments
SET
    status = 'PAID',
    razorpay_payment_id = COALESCE(razorpay_payment_id, $2),
    updated_at = NOW()
WHERE razorpay_order_id = $1
  AND (status = 'CREATED' OR (status = 'PAID' AND (razorpay_payment_id IS NULL OR razorpay_payment_id = $2)))
RETURNING id, public_id, user_id, razorpay_order_id, razorpay_payment_id, amount, currency, status, receipt, created_at, updated_at
`

type MarkPaymentPaidIdempotentParams struct {
	RazorpayOrderID   string
	RazorpayPaymentID pgtype.Text
}

func (q *Queries) MarkPaymentPaidIdempotent(ctx context.Context, arg MarkPaymentPaidIdempotentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaidIdempotent, arg.RazorpayOrderID, arg.RazorpayPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RazorpayOrderID,
		&i.RazorpayPaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Receipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
