// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_registrations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredPendingRegistrations = `-- name: DeleteExpiredPendingRegistrations :exec
DELETE FROM pending_registrations
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredPendingRegistrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingRegistrations)
	return err
}

const deletePendingRegistrationByID = `-- name: DeletePendingRegistrationByID :exec
DELETE FROM pending_registrations
WHERE id = $1
`

func (q *Queries) DeletePendingRegistrationByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePendingRegistrationByID, id)
	return err
}

const getActivePendingRegistrationByEmail = `-- name: GetActivePendingRegistrationByEmail :one
SELECT id, email, username, name, password_hash, otp_hash, expires_at, created_at, updated_at
FROM pending_registrations
WHERE email = $1
  AND expires_at > NOW()
`

func (q *Queries) GetActivePendingRegistrationByEmail(ctx context.Context, email string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getActivePendingRegistrationByEmail, email)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePendingRegistrationByUsername = `-- name: GetActivePendingRegistrationByUsername :one
SELECT id, email, username, name, password_hash, otp_hash, expires_at, created_at, updated_at
FROM pending_registrations
WHERE username = $1
  AND expires_at > NOW()
`

func (q *Queries) GetActivePendingRegistrationByUsername(ctx context.Context, username string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getActivePendingRegistrationByUsername, username)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRegistrationByEmail = `-- name: GetPendingRegistrationByEmail :one
SELECT id, email, username, name, password_hash, otp_hash, expires_at, created_at, updated_at
FROM pending_registrations
WHERE email = $1
`

func (q *Queries) GetPendingRegistrationByEmail(ctx context.Context, email string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByEmail, email)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingRegistrationOTP = `-- name: UpdatePendingRegistrationOTP :one
UPDATE pending_registrations
SET
    otp_hash = $2,
    expires_at = $3,
    updated_at = NOW()
WHERE email = $1
RETURNING id, email, username, name, password_hash, otp_hash, expires_at, created_at, updated_at
`

type UpdatePendingRegistrationOTPParams struct {
	Email     string
	OtpHash   string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdatePendingRegistrationOTP(ctx context.Context, arg UpdatePendingRegistrationOTPParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, updatePendingRegistrationOTP, arg.Email, arg.OtpHash, arg.ExpiresAt)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingRegistration = `-- name: UpsertPendingRegistration :one

INSERT INTO pending_registrations (
    email,
    username,
    name,
    password_hash,
    otp_hash,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (email) DO UPDATE
SET
    username = EXCLUDED.username,
    name = EXCLUDED.name,
    password_hash = EXCLUDED.password_hash,
    otp_hash = EXCLUDED.otp_hash,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
RETURNING id, email, username, name, password_hash, otp_hash, expires_at, created_at, updated_at
`

type UpsertPendingRegistrationParams struct {
	Email        string
	Username     string
	Name         string
	PasswordHash string
	OtpHash      string
	ExpiresAt    pgtype.Timestamptz
}

// =========================================
// PENDING REGISTRATIONS (pre-OTP)
// =========================================
func (q *Queries) UpsertPendingRegistration(ctx context.Context, arg UpsertPendingRegistrationParams) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, upsertPendingRegistration,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.PasswordHash,
		arg.OtpHash,
		arg.ExpiresAt,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.OtpHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
