// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAcceptedPodMembers = `-- name: CountAcceptedPodMembers :one
SELECT COUNT(*)::bigint
FROM pod_membership
WHERE pod_id = $1
  AND status = 'ACCEPTED'
`

func (q *Queries) CountAcceptedPodMembers(ctx context.Context, podID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptedPodMembers, podID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPod = `-- name: CreatePod :one

INSERT INTO pods (
    slug,
    name,
    description,
    owner_id,
    skill_id,
    max_members
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, slug, name, description, owner_id, skill_id, max_members, created_at, updated_at
`

type CreatePodParams struct {
	Slug        string
	Name        string
	Description pgtype.Text
	OwnerID     int64
	SkillID     int64
	MaxMembers  int32
}

// =========================================
// PODS
// =========================================
func (q *Queries) CreatePod(ctx context.Context, arg CreatePodParams) (Pod, error) {
	row := q.db.QueryRow(ctx, createPod,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.SkillID,
		arg.MaxMembers,
	)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.SkillID,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePod = `-- name: DeletePod :exec
DELETE FROM pods
WHERE id = $1
`

func (q *Queries) DeletePod(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePod, id)
	return err
}

const getPodByID = `-- name: GetPodByID :one
SELECT id, public_id, slug, name, description, owner_id, skill_id, max_members, created_at, updated_at
FROM pods
WHERE id = $1
`

func (q *Queries) GetPodByID(ctx context.Context, id int64) (Pod, error) {
	row := q.db.QueryRow(ctx, getPodByID, id)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.SkillID,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPodBySlug = `-- name: GetPodBySlug :one
SELECT
    p.id,
    p.public_id,
    p.slug,
    p.name,
    p.description,
    p.owner_id,
    p.skill_id,
    p.max_members,
    p.created_at,
    p.updated_at,
    s.slug AS skill_slug,
    s.name AS skill_name,
    u.username AS owner_username
FROM pods p
INNER JOIN skills s ON s.id = p.skill_id
INNER JOIN users u ON u.id = p.owner_id
WHERE p.slug = $1
`

type GetPodBySlugRow struct {
	ID            int64
	PublicID      uuid.UUID
	Slug          string
	Name          string
	Description   pgtype.Text
	OwnerID       int64
	SkillID       int64
	MaxMembers    int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SkillSlug     string
	SkillName     string
	OwnerUsername string
}

func (q *Queries) GetPodBySlug(ctx context.Context, slug string) (GetPodBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPodBySlug, slug)
	var i GetPodBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.SkillID,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SkillSlug,
		&i.SkillName,
		&i.OwnerUsername,
	)
	return i, err
}

const listPodsBySkillSlug = `-- name: ListPodsBySkillSlug :many
SELECT
    p.id,
    p.public_id,
    p.slug,
    p.name,
    p.description,
    p.owner_id,
    p.skill_id,
    p.max_members,
    p.created_at,
    p.updated_at,
    s.slug AS skill_slug,
    s.name AS skill_name,
    u.username AS owner_username,
    (
        SELECT COUNT(*)::bigint
        FROM pod_membership pm
        WHERE pm.pod_id = p.id
          AND pm.status = 'ACCEPTED'
    ) AS accepted_count
FROM pods p
INNER JOIN skills s ON s.id = p.skill_id
INNER JOIN users u ON u.id = p.owner_id
WHERE s.slug = $1
ORDER BY p.created_at DESC
`

type ListPodsBySkillSlugRow struct {
	ID            int64
	PublicID      uuid.UUID
	Slug          string
	Name          string
	Description   pgtype.Text
	OwnerID       int64
	SkillID       int64
	MaxMembers    int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	SkillSlug     string
	SkillName     string
	OwnerUsername string
	AcceptedCount int64
}

func (q *Queries) ListPodsBySkillSlug(ctx context.Context, slug string) ([]ListPodsBySkillSlugRow, error) {
	rows, err := q.db.Query(ctx, listPodsBySkillSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPodsBySkillSlugRow
	for rows.Next() {
		var i ListPodsBySkillSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.SkillID,
			&i.MaxMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SkillSlug,
			&i.SkillName,
			&i.OwnerUsername,
			&i.AcceptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const podSlugExists = `-- name: PodSlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM pods
    WHERE slug = $1
)
`

func (q *Queries) PodSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, podSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePodOwner = `-- name: UpdatePodOwner :one
UPDATE pods
SET
    owner_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, slug, name, description, owner_id, skill_id, max_members, created_at, updated_at
`

type UpdatePodOwnerParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) UpdatePodOwner(ctx context.Context, arg UpdatePodOwnerParams) (Pod, error) {
	row := q.db.QueryRow(ctx, updatePodOwner, arg.ID, arg.OwnerID)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.SkillID,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
