// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlc

import (
	"context"
)

const updateUsername = `-- name: UpdateUsername :one
UPDATE users
SET
    username = $2,
    updated_at = NOW()
WHERE id = $1
    AND is_deleted = FALSE
RETURNING id, public_id, email, username, name, profile_picture_url, bio, subscription, email_verified, is_deleted, deleted_at, created_at, updated_at, role
`

type UpdateUsernameParams struct {
	ID       int64
	Username string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.Bio,
		&i.Subscription,
		&i.EmailVerified,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const usernameHistoryExists = `-- name: UsernameHistoryExists :one

SELECT EXISTS (
    SELECT 1
    FROM username_history
    WHERE username = $1
)
`

// =========================================
// USERNAME
// =========================================
func (q *Queries) UsernameHistoryExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameHistoryExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
