// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const abandonPodQuiz = `-- name: AbandonPodQuiz :one
UPDATE pod_quiz
SET status = 'ABANDONED'
WHERE id = $1
  AND status IN ('IN_PROGRESS', 'GENERATING')
RETURNING id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at
`

func (q *Queries) AbandonPodQuiz(ctx context.Context, id int64) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, abandonPodQuiz, id)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const activatePodQuiz = `-- name: ActivatePodQuiz :one
UPDATE pod_quiz
SET status = 'IN_PROGRESS'
WHERE id = $1
  AND status = 'GENERATING'
RETURNING id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at
`

func (q *Queries) ActivatePodQuiz(ctx context.Context, id int64) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, activatePodQuiz, id)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completePodQuiz = `-- name: CompletePodQuiz :one
UPDATE pod_quiz
SET
    status = 'COMPLETED',
    correct_count = $2,
    score = $3,
    completed_at = NOW()
WHERE id = $1
  AND status = 'IN_PROGRESS'
RETURNING id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at
`

type CompletePodQuizParams struct {
	ID           int64
	CorrectCount int32
	Score        int32
}

func (q *Queries) CompletePodQuiz(ctx context.Context, arg CompletePodQuizParams) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, completePodQuiz, arg.ID, arg.CorrectCount, arg.Score)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCorrectPodQuizAnswers = `-- name: CountCorrectPodQuizAnswers :one
SELECT COUNT(*)::bigint
FROM pod_quiz_answer
WHERE quiz_id = $1
  AND is_correct = TRUE
  AND answered_at IS NOT NULL
`

func (q *Queries) CountCorrectPodQuizAnswers(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCorrectPodQuizAnswers, quizID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPodQuiz = `-- name: CreatePodQuiz :one
INSERT INTO pod_quiz (
    pod_id,
    user_id,
    skill_id,
    status,
    topic_count,
    completed_topic_titles
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at
`

type CreatePodQuizParams struct {
	PodID                int64
	UserID               int64
	SkillID              int64
	Status               PodQuizStatus
	TopicCount           int32
	CompletedTopicTitles []byte
}

func (q *Queries) CreatePodQuiz(ctx context.Context, arg CreatePodQuizParams) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, createPodQuiz,
		arg.PodID,
		arg.UserID,
		arg.SkillID,
		arg.Status,
		arg.TopicCount,
		arg.CompletedTopicTitles,
	)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createPodQuizQuestion = `-- name: CreatePodQuizQuestion :one
INSERT INTO pod_quiz_question (
    quiz_id,
    order_index,
    difficulty,
    prompt,
    options,
    correct_indices,
    topic_title,
    weight
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, quiz_id, order_index, difficulty, prompt, options, correct_indices, topic_title, weight
`

type CreatePodQuizQuestionParams struct {
	QuizID         int64
	OrderIndex     int32
	Difficulty     int32
	Prompt         string
	Options        []byte
	CorrectIndices []byte
	TopicTitle     string
	Weight         int32
}

func (q *Queries) CreatePodQuizQuestion(ctx context.Context, arg CreatePodQuizQuestionParams) (PodQuizQuestion, error) {
	row := q.db.QueryRow(ctx, createPodQuizQuestion,
		arg.QuizID,
		arg.OrderIndex,
		arg.Difficulty,
		arg.Prompt,
		arg.Options,
		arg.CorrectIndices,
		arg.TopicTitle,
		arg.Weight,
	)
	var i PodQuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.OrderIndex,
		&i.Difficulty,
		&i.Prompt,
		&i.Options,
		&i.CorrectIndices,
		&i.TopicTitle,
		&i.Weight,
	)
	return i, err
}

const failPodQuiz = `-- name: FailPodQuiz :one
UPDATE pod_quiz
SET status = 'FAILED'
WHERE id = $1
  AND status = 'GENERATING'
RETURNING id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at
`

func (q *Queries) FailPodQuiz(ctx context.Context, id int64) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, failPodQuiz, id)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getInProgressPodQuiz = `-- name: GetInProgressPodQuiz :one
SELECT id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at FROM pod_quiz
WHERE user_id = $1
  AND pod_id = $2
  AND status IN ('IN_PROGRESS', 'GENERATING')
`

type GetInProgressPodQuizParams struct {
	UserID int64
	PodID  int64
}

func (q *Queries) GetInProgressPodQuiz(ctx context.Context, arg GetInProgressPodQuizParams) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, getInProgressPodQuiz, arg.UserID, arg.PodID)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPodQuizAnswer = `-- name: GetPodQuizAnswer :one
SELECT id, quiz_id, question_id, selected_indices, is_correct, started_at, answered_at, timed_out FROM pod_quiz_answer
WHERE quiz_id = $1
  AND question_id = $2
`

type GetPodQuizAnswerParams struct {
	QuizID     int64
	QuestionID int64
}

func (q *Queries) GetPodQuizAnswer(ctx context.Context, arg GetPodQuizAnswerParams) (PodQuizAnswer, error) {
	row := q.db.QueryRow(ctx, getPodQuizAnswer, arg.QuizID, arg.QuestionID)
	var i PodQuizAnswer
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionID,
		&i.SelectedIndices,
		&i.IsCorrect,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.TimedOut,
	)
	return i, err
}

const getPodQuizByID = `-- name: GetPodQuizByID :one
SELECT id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at FROM pod_quiz
WHERE id = $1
`

func (q *Queries) GetPodQuizByID(ctx context.Context, id int64) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, getPodQuizByID, id)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPodQuizByPublicID = `-- name: GetPodQuizByPublicID :one
SELECT id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at FROM pod_quiz
WHERE public_id = $1
`

func (q *Queries) GetPodQuizByPublicID(ctx context.Context, publicID uuid.UUID) (PodQuiz, error) {
	row := q.db.QueryRow(ctx, getPodQuizByPublicID, publicID)
	var i PodQuiz
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PodID,
		&i.UserID,
		&i.SkillID,
		&i.Status,
		&i.TopicCount,
		&i.CorrectCount,
		&i.Score,
		&i.CompletedTopicTitles,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPodQuizQuestionByOrder = `-- name: GetPodQuizQuestionByOrder :one
SELECT id, quiz_id, order_index, difficulty, prompt, options, correct_indices, topic_title, weight FROM pod_quiz_question
WHERE quiz_id = $1
  AND order_index = $2
`

type GetPodQuizQuestionByOrderParams struct {
	QuizID     int64
	OrderIndex int32
}

func (q *Queries) GetPodQuizQuestionByOrder(ctx context.Context, arg GetPodQuizQuestionByOrderParams) (PodQuizQuestion, error) {
	row := q.db.QueryRow(ctx, getPodQuizQuestionByOrder, arg.QuizID, arg.OrderIndex)
	var i PodQuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.OrderIndex,
		&i.Difficulty,
		&i.Prompt,
		&i.Options,
		&i.CorrectIndices,
		&i.TopicTitle,
		&i.Weight,
	)
	return i, err
}

const listCommunityPodLeaderboard = `-- name: ListCommunityPodLeaderboard :many
WITH best AS (
    SELECT
        pq.pod_id,
        pq.user_id,
        MAX(pq.score)::int AS best_score
    FROM pod_quiz pq
    INNER JOIN pods p ON p.id = pq.pod_id
    WHERE p.skill_id = $1
      AND pq.status = 'COMPLETED'
    GROUP BY pq.pod_id, pq.user_id
),
pod_totals AS (
    SELECT
        p.id AS pod_id,
        p.slug AS pod_slug,
        p.name AS pod_name,
        COALESCE(SUM(b.best_score), 0)::int AS total_score,
        COUNT(DISTINCT pm.user_id)::int AS member_count
    FROM pods p
    INNER JOIN pod_membership pm ON pm.pod_id = p.id AND pm.status = 'ACCEPTED'
    LEFT JOIN best b ON b.pod_id = p.id AND b.user_id = pm.user_id
    WHERE p.skill_id = $1
    GROUP BY p.id, p.slug, p.name
)
SELECT pod_id, pod_slug, pod_name, total_score, member_count
FROM pod_totals
ORDER BY total_score DESC, pod_name ASC
`

type ListCommunityPodLeaderboardRow struct {
	PodID       int64
	PodSlug     string
	PodName     string
	TotalScore  int32
	MemberCount int32
}

func (q *Queries) ListCommunityPodLeaderboard(ctx context.Context, skillID int64) ([]ListCommunityPodLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listCommunityPodLeaderboard, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunityPodLeaderboardRow
	for rows.Next() {
		var i ListCommunityPodLeaderboardRow
		if err := rows.Scan(
			&i.PodID,
			&i.PodSlug,
			&i.PodName,
			&i.TotalScore,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedTopicTitlesForUserSkill = `-- name: ListCompletedTopicTitlesForUserSkill :many
SELECT m.title
FROM userskill us
INNER JOIN user_milestone_progress ump ON ump.user_skill_id = us.id
INNER JOIN milestones m ON m.id = ump.milestone_id
WHERE us.user_id = $1
  AND us.skill_id = $2
  AND ump.status = 'COMPLETED'
  AND m.kind = 'TOPIC'
  AND m.roadmap_version_id = us.roadmap_version_id
ORDER BY m.order_index
`

type ListCompletedTopicTitlesForUserSkillParams struct {
	UserID  int64
	SkillID int64
}

func (q *Queries) ListCompletedTopicTitlesForUserSkill(ctx context.Context, arg ListCompletedTopicTitlesForUserSkillParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listCompletedTopicTitlesForUserSkill, arg.UserID, arg.SkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var title string
		if err := rows.Scan(&title); err != nil {
			return nil, err
		}
		items = append(items, title)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneratingPodQuizzes = `-- name: ListGeneratingPodQuizzes :many
SELECT id
FROM pod_quiz
WHERE status = 'GENERATING'
ORDER BY created_at ASC
`

func (q *Queries) ListGeneratingPodQuizzes(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGeneratingPodQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPodQuizzes = `-- name: ListMyPodQuizzes :many
SELECT id, public_id, pod_id, user_id, skill_id, status, topic_count, correct_count, score, completed_topic_titles, created_at, completed_at FROM pod_quiz
WHERE user_id = $1
  AND pod_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMyPodQuizzesParams struct {
	UserID int64
	PodID  int64
	Limit  int32
}

func (q *Queries) ListMyPodQuizzes(ctx context.Context, arg ListMyPodQuizzesParams) ([]PodQuiz, error) {
	rows, err := q.db.Query(ctx, listMyPodQuizzes, arg.UserID, arg.PodID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodQuiz
	for rows.Next() {
		var i PodQuiz
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.PodID,
			&i.UserID,
			&i.SkillID,
			&i.Status,
			&i.TopicCount,
			&i.CorrectCount,
			&i.Score,
			&i.CompletedTopicTitles,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodLeaderboard = `-- name: ListPodLeaderboard :many
WITH best AS (
    SELECT
        pq.user_id,
        MAX(pq.score)::int AS best_score,
        MAX(pq.topic_count)::int AS topic_count
    FROM pod_quiz pq
    WHERE pq.pod_id = $1
      AND pq.status = 'COMPLETED'
    GROUP BY pq.user_id
),
members AS (
    SELECT pm.user_id, u.username, u.public_id, u.name
    FROM pod_membership pm
    INNER JOIN users u ON u.id = pm.user_id
    WHERE pm.pod_id = $1
      AND pm.status = 'ACCEPTED'
)
SELECT
    m.username,
    m.public_id,
    m.name,
    COALESCE(b.best_score, 0)::int AS best_score,
    COALESCE(b.topic_count, 0)::int AS topic_count
FROM members m
LEFT JOIN best b ON b.user_id = m.user_id
ORDER BY best_score DESC, m.username ASC
`

type ListPodLeaderboardRow struct {
	Username   string
	PublicID   uuid.UUID
	Name       string
	BestScore  int32
	TopicCount int32
}

func (q *Queries) ListPodLeaderboard(ctx context.Context, podID int64) ([]ListPodLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listPodLeaderboard, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPodLeaderboardRow
	for rows.Next() {
		var i ListPodLeaderboardRow
		if err := rows.Scan(
			&i.Username,
			&i.PublicID,
			&i.Name,
			&i.BestScore,
			&i.TopicCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodQuizQuestions = `-- name: ListPodQuizQuestions :many
SELECT id, quiz_id, order_index, difficulty, prompt, options, correct_indices, topic_title, weight FROM pod_quiz_question
WHERE quiz_id = $1
ORDER BY order_index
`

func (q *Queries) ListPodQuizQuestions(ctx context.Context, quizID int64) ([]PodQuizQuestion, error) {
	rows, err := q.db.Query(ctx, listPodQuizQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodQuizQuestion
	for rows.Next() {
		var i PodQuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.OrderIndex,
			&i.Difficulty,
			&i.Prompt,
			&i.Options,
			&i.CorrectIndices,
			&i.TopicTitle,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePodQuizAnswer = `-- name: SavePodQuizAnswer :one
UPDATE pod_quiz_answer
SET
    selected_indices = $3,
    is_correct = $4,
    answered_at = NOW(),
    timed_out = $5
WHERE quiz_id = $1
  AND question_id = $2
  AND answered_at IS NULL
RETURNING id, quiz_id, question_id, selected_indices, is_correct, started_at, answered_at, timed_out
`

type SavePodQuizAnswerParams struct {
	QuizID          int64
	QuestionID      int64
	SelectedIndices []byte
	IsCorrect       bool
	TimedOut        bool
}

func (q *Queries) SavePodQuizAnswer(ctx context.Context, arg SavePodQuizAnswerParams) (PodQuizAnswer, error) {
	row := q.db.QueryRow(ctx, savePodQuizAnswer,
		arg.QuizID,
		arg.QuestionID,
		arg.SelectedIndices,
		arg.IsCorrect,
		arg.TimedOut,
	)
	var i PodQuizAnswer
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionID,
		&i.SelectedIndices,
		&i.IsCorrect,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.TimedOut,
	)
	return i, err
}

const upsertPodQuizAnswerStart = `-- name: UpsertPodQuizAnswerStart :one
INSERT INTO pod_quiz_answer (quiz_id, question_id, started_at)
VALUES ($1, $2, NOW())
ON CONFLICT (quiz_id, question_id) DO UPDATE
SET started_at = COALESCE(pod_quiz_answer.started_at, EXCLUDED.started_at)
RETURNING id, quiz_id, question_id, selected_indices, is_correct, started_at, answered_at, timed_out
`

type UpsertPodQuizAnswerStartParams struct {
	QuizID     int64
	QuestionID int64
}

func (q *Queries) UpsertPodQuizAnswerStart(ctx context.Context, arg UpsertPodQuizAnswerStartParams) (PodQuizAnswer, error) {
	row := q.db.QueryRow(ctx, upsertPodQuizAnswerStart, arg.QuizID, arg.QuestionID)
	var i PodQuizAnswer
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionID,
		&i.SelectedIndices,
		&i.IsCorrect,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.TimedOut,
	)
	return i, err
}
