// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"
)

const createReport = `-- name: CreateReport :one

INSERT INTO report (
    reporter_id,
    target_type,
    target_id,
    reason,
    status
)
VALUES ($1, $2, $3, $4, 'OPEN')
RETURNING
    id,
    reporter_id,
    target_type,
    target_id,
    reason,
    status,
    resolved_at,
    resolved_by,
    created_at,
    updated_at
`

type CreateReportParams struct {
	ReporterID int64
	TargetType ReportTargetType
	TargetID   int64
	Reason     string
}

// =========================================
// REPORTS
// =========================================
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenReportByReporterAndTarget = `-- name: GetOpenReportByReporterAndTarget :one
SELECT
    id,
    reporter_id,
    target_type,
    target_id,
    reason,
    status,
    resolved_at,
    resolved_by,
    created_at,
    updated_at
FROM report
WHERE reporter_id = $1
  AND target_type = $2
  AND target_id = $3
  AND status = 'OPEN'
LIMIT 1
`

type GetOpenReportByReporterAndTargetParams struct {
	ReporterID int64
	TargetType ReportTargetType
	TargetID   int64
}

func (q *Queries) GetOpenReportByReporterAndTarget(ctx context.Context, arg GetOpenReportByReporterAndTargetParams) (Report, error) {
	row := q.db.QueryRow(ctx, getOpenReportByReporterAndTarget, arg.ReporterID, arg.TargetType, arg.TargetID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByIDAndReporterID = `-- name: GetReportByIDAndReporterID :one
SELECT
    id,
    reporter_id,
    target_type,
    target_id,
    reason,
    status,
    resolved_at,
    resolved_by,
    created_at,
    updated_at
FROM report
WHERE id = $1
  AND reporter_id = $2
`

type GetReportByIDAndReporterIDParams struct {
	ID         int64
	ReporterID int64
}

func (q *Queries) GetReportByIDAndReporterID(ctx context.Context, arg GetReportByIDAndReporterIDParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByIDAndReporterID, arg.ID, arg.ReporterID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportsByReporterID = `-- name: ListReportsByReporterID :many
SELECT
    id,
    reporter_id,
    target_type,
    target_id,
    reason,
    status,
    resolved_at,
    resolved_by,
    created_at,
    updated_at
FROM report
WHERE reporter_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListReportsByReporterIDParams struct {
	ReporterID int64
	Limit      int32
}

func (q *Queries) ListReportsByReporterID(ctx context.Context, arg ListReportsByReporterIDParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByReporterID, arg.ReporterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
