// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roadmaps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveRoadmapVersionBySkillID = `-- name: GetActiveRoadmapVersionBySkillID :one
SELECT rv.id, rv.roadmap_id, rv.version_number, rv.status, rv.generated_by, rv.published_at, rv.created_at
FROM roadmap_version rv
INNER JOIN roadmaps r ON r.id = rv.roadmap_id
WHERE r.skill_id = $1
  AND rv.status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveRoadmapVersionBySkillID(ctx context.Context, skillID int64) (RoadmapVersion, error) {
	row := q.db.QueryRow(ctx, getActiveRoadmapVersionBySkillID, skillID)
	var i RoadmapVersion
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentRoadmapVersionBySkillID = `-- name: GetCurrentRoadmapVersionBySkillID :one
SELECT rv.id, rv.roadmap_id, rv.version_number, rv.status, rv.generated_by, rv.published_at, rv.created_at
FROM roadmaps r
INNER JOIN roadmap_version rv ON rv.id = COALESCE(
    r.current_version_id,
    (
        SELECT rv2.id
        FROM roadmap_version rv2
        WHERE rv2.roadmap_id = r.id
          AND rv2.status = 'ACTIVE'
        ORDER BY rv2.version_number DESC
        LIMIT 1
    )
)
WHERE r.skill_id = $1
`

// Prefer roadmaps.current_version_id; fall back to ACTIVE status.
func (q *Queries) GetCurrentRoadmapVersionBySkillID(ctx context.Context, skillID int64) (RoadmapVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentRoadmapVersionBySkillID, skillID)
	var i RoadmapVersion
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadmapBySkillID = `-- name: GetRoadmapBySkillID :one

SELECT id, current_version_id, skill_id, created_at, updated_at
FROM roadmaps
WHERE skill_id = $1
`

// =========================================
// GET
// =========================================
func (q *Queries) GetRoadmapBySkillID(ctx context.Context, skillID int64) (Roadmap, error) {
	row := q.db.QueryRow(ctx, getRoadmapBySkillID, skillID)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.CurrentVersionID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoadmapBySkillSlug = `-- name: GetRoadmapBySkillSlug :one
SELECT r.id, r.current_version_id, r.skill_id, r.created_at, r.updated_at,
       s.slug AS skill_slug, s.name AS skill_name
FROM roadmaps r
INNER JOIN skills s ON s.id = r.skill_id
WHERE s.slug = $1
`

type GetRoadmapBySkillSlugRow struct {
	ID               int64
	CurrentVersionID pgtype.Int8
	SkillID          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SkillSlug        string
	SkillName        string
}

func (q *Queries) GetRoadmapBySkillSlug(ctx context.Context, slug string) (GetRoadmapBySkillSlugRow, error) {
	row := q.db.QueryRow(ctx, getRoadmapBySkillSlug, slug)
	var i GetRoadmapBySkillSlugRow
	err := row.Scan(
		&i.ID,
		&i.CurrentVersionID,
		&i.SkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SkillSlug,
		&i.SkillName,
	)
	return i, err
}

const getRoadmapVersionByID = `-- name: GetRoadmapVersionByID :one
SELECT id, roadmap_id, version_number, status, generated_by, published_at, created_at
FROM roadmap_version
WHERE id = $1
`

func (q *Queries) GetRoadmapVersionByID(ctx context.Context, id int64) (RoadmapVersion, error) {
	row := q.db.QueryRow(ctx, getRoadmapVersionByID, id)
	var i RoadmapVersion
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadmapVersionBySkillSlugAndNumber = `-- name: GetRoadmapVersionBySkillSlugAndNumber :one
SELECT rv.id, rv.roadmap_id, rv.version_number, rv.status, rv.generated_by, rv.published_at, rv.created_at,
       COALESCE(r.current_version_id = rv.id, false)::boolean AS is_current,
       s.slug AS skill_slug, s.name AS skill_name
FROM roadmap_version rv
INNER JOIN roadmaps r ON r.id = rv.roadmap_id
INNER JOIN skills s ON s.id = r.skill_id
WHERE s.slug = $1
  AND rv.version_number = $2
`

type GetRoadmapVersionBySkillSlugAndNumberParams struct {
	Slug          string
	VersionNumber int32
}

type GetRoadmapVersionBySkillSlugAndNumberRow struct {
	ID            int64
	RoadmapID     pgtype.Int8
	VersionNumber int32
	Status        CurrentStatus
	GeneratedBy   string
	PublishedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	IsCurrent     bool
	SkillSlug     string
	SkillName     string
}

func (q *Queries) GetRoadmapVersionBySkillSlugAndNumber(ctx context.Context, arg GetRoadmapVersionBySkillSlugAndNumberParams) (GetRoadmapVersionBySkillSlugAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getRoadmapVersionBySkillSlugAndNumber, arg.Slug, arg.VersionNumber)
	var i GetRoadmapVersionBySkillSlugAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.RoadmapID,
		&i.VersionNumber,
		&i.Status,
		&i.GeneratedBy,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.IsCurrent,
		&i.SkillSlug,
		&i.SkillName,
	)
	return i, err
}

const listRoadmapVersionsBySkillSlug = `-- name: ListRoadmapVersionsBySkillSlug :many
SELECT rv.id, rv.roadmap_id, rv.version_number, rv.status, rv.generated_by, rv.published_at, rv.created_at,
       COALESCE(r.current_version_id = rv.id, false)::boolean AS is_current,
       (
           SELECT COUNT(*)::bigint
           FROM milestones m
           WHERE m.roadmap_version_id = rv.id
       ) AS milestone_count
FROM roadmap_version rv
INNER JOIN roadmaps r ON r.id = rv.roadmap_id
INNER JOIN skills s ON s.id = r.skill_id
WHERE s.slug = $1
ORDER BY rv.version_number DESC
`

type ListRoadmapVersionsBySkillSlugRow struct {
	ID             int64
	RoadmapID      pgtype.Int8
	VersionNumber  int32
	Status         CurrentStatus
	GeneratedBy    string
	PublishedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	IsCurrent      bool
	MilestoneCount int64
}

func (q *Queries) ListRoadmapVersionsBySkillSlug(ctx context.Context, slug string) ([]ListRoadmapVersionsBySkillSlugRow, error) {
	rows, err := q.db.Query(ctx, listRoadmapVersionsBySkillSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoadmapVersionsBySkillSlugRow
	for rows.Next() {
		var i ListRoadmapVersionsBySkillSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapID,
			&i.VersionNumber,
			&i.Status,
			&i.GeneratedBy,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.IsCurrent,
			&i.MilestoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
