// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveParticipants = `-- name: CountActiveParticipants :one
SELECT COUNT(*)::bigint
FROM audio_room_participant
WHERE audio_room_id = $1
  AND left_at IS NULL
`

func (q *Queries) CountActiveParticipants(ctx context.Context, audioRoomID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveParticipants, audioRoomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAudioRoom = `-- name: CreateAudioRoom :one

INSERT INTO audio_room (
    public_id,
    room_type,
    pod_id,
    community_channel_id,
    host_id,
    title,
    description,
    livekit_room_name,
    status,
    actual_start_time,
    max_participants
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id,
    public_id,
    room_type,
    pod_id,
    community_channel_id,
    host_id,
    title,
    description,
    livekit_room_name,
    status,
    scheduled_start_time,
    actual_start_time,
    ended_at,
    max_participants,
    created_at,
    updated_at
`

type CreateAudioRoomParams struct {
	PublicID           uuid.UUID
	RoomType           AudioRoomType
	PodID              pgtype.Int8
	CommunityChannelID pgtype.Int8
	HostID             int64
	Title              string
	Description        pgtype.Text
	LivekitRoomName    string
	Status             AudioRoomStatus
	ActualStartTime    pgtype.Timestamptz
	MaxParticipants    pgtype.Int4
}

// =========================================
// AUDIO ROOMS
// =========================================
func (q *Queries) CreateAudioRoom(ctx context.Context, arg CreateAudioRoomParams) (AudioRoom, error) {
	row := q.db.QueryRow(ctx, createAudioRoom,
		arg.PublicID,
		arg.RoomType,
		arg.PodID,
		arg.CommunityChannelID,
		arg.HostID,
		arg.Title,
		arg.Description,
		arg.LivekitRoomName,
		arg.Status,
		arg.ActualStartTime,
		arg.MaxParticipants,
	)
	var i AudioRoom
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RoomType,
		&i.PodID,
		&i.CommunityChannelID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.LivekitRoomName,
		&i.Status,
		&i.ScheduledStartTime,
		&i.ActualStartTime,
		&i.EndedAt,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAudioRoom = `-- name: DeleteAudioRoom :exec
DELETE FROM audio_room
WHERE id = $1
`

func (q *Queries) DeleteAudioRoom(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAudioRoom, id)
	return err
}

const endAllActiveAudioRooms = `-- name: EndAllActiveAudioRooms :execrows
UPDATE audio_room
SET
    status = 'ENDED',
    ended_at = NOW(),
    updated_at = NOW()
WHERE status = 'ACTIVE'
`

func (q *Queries) EndAllActiveAudioRooms(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, endAllActiveAudioRooms)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endAudioRoom = `-- name: EndAudioRoom :one
UPDATE audio_room
SET
    status = 'ENDED',
    ended_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
RETURNING
    id,
    public_id,
    room_type,
    pod_id,
    community_channel_id,
    host_id,
    title,
    description,
    livekit_room_name,
    status,
    scheduled_start_time,
    actual_start_time,
    ended_at,
    max_participants,
    created_at,
    updated_at
`

func (q *Queries) EndAudioRoom(ctx context.Context, id int64) (AudioRoom, error) {
	row := q.db.QueryRow(ctx, endAudioRoom, id)
	var i AudioRoom
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RoomType,
		&i.PodID,
		&i.CommunityChannelID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.LivekitRoomName,
		&i.Status,
		&i.ScheduledStartTime,
		&i.ActualStartTime,
		&i.EndedAt,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAudioRoomByChannelID = `-- name: GetActiveAudioRoomByChannelID :one
SELECT id, public_id, room_type, pod_id, community_channel_id, host_id, title, description,
       livekit_room_name, status, scheduled_start_time, actual_start_time, ended_at,
       max_participants, created_at, updated_at
FROM audio_room
WHERE community_channel_id = $1
  AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveAudioRoomByChannelID(ctx context.Context, communityChannelID pgtype.Int8) (AudioRoom, error) {
	row := q.db.QueryRow(ctx, getActiveAudioRoomByChannelID, communityChannelID)
	var i AudioRoom
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RoomType,
		&i.PodID,
		&i.CommunityChannelID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.LivekitRoomName,
		&i.Status,
		&i.ScheduledStartTime,
		&i.ActualStartTime,
		&i.EndedAt,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAudioRoomByPodID = `-- name: GetActiveAudioRoomByPodID :one
SELECT id, public_id, room_type, pod_id, community_channel_id, host_id, title, description,
       livekit_room_name, status, scheduled_start_time, actual_start_time, ended_at,
       max_participants, created_at, updated_at
FROM audio_room
WHERE pod_id = $1
  AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveAudioRoomByPodID(ctx context.Context, podID pgtype.Int8) (AudioRoom, error) {
	row := q.db.QueryRow(ctx, getActiveAudioRoomByPodID, podID)
	var i AudioRoom
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RoomType,
		&i.PodID,
		&i.CommunityChannelID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.LivekitRoomName,
		&i.Status,
		&i.ScheduledStartTime,
		&i.ActualStartTime,
		&i.EndedAt,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAudioRoomByPublicID = `-- name: GetAudioRoomByPublicID :one
SELECT
    ar.id,
    ar.public_id,
    ar.room_type,
    ar.pod_id,
    ar.community_channel_id,
    ar.host_id,
    ar.title,
    ar.description,
    ar.livekit_room_name,
    ar.status,
    ar.scheduled_start_time,
    ar.actual_start_time,
    ar.ended_at,
    ar.max_participants,
    ar.created_at,
    ar.updated_at,
    u.username AS host_username,
    p.slug AS pod_slug,
    s.slug AS skill_slug,
    cc.slug AS channel_slug
FROM audio_room ar
INNER JOIN users u ON u.id = ar.host_id
LEFT JOIN pods p ON p.id = ar.pod_id
LEFT JOIN community_channel cc ON cc.id = ar.community_channel_id
LEFT JOIN community c ON c.id = cc.community_id
LEFT JOIN skills s ON s.id = c.skill_id
WHERE ar.public_id = $1
`

type GetAudioRoomByPublicIDRow struct {
	ID                 int64
	PublicID           uuid.UUID
	RoomType           AudioRoomType
	PodID              pgtype.Int8
	CommunityChannelID pgtype.Int8
	HostID             int64
	Title              string
	Description        pgtype.Text
	LivekitRoomName    string
	Status             AudioRoomStatus
	ScheduledStartTime pgtype.Timestamptz
	ActualStartTime    pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	MaxParticipants    pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	HostUsername       string
	PodSlug            pgtype.Text
	SkillSlug          pgtype.Text
	ChannelSlug        pgtype.Text
}

func (q *Queries) GetAudioRoomByPublicID(ctx context.Context, publicID uuid.UUID) (GetAudioRoomByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getAudioRoomByPublicID, publicID)
	var i GetAudioRoomByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RoomType,
		&i.PodID,
		&i.CommunityChannelID,
		&i.HostID,
		&i.Title,
		&i.Description,
		&i.LivekitRoomName,
		&i.Status,
		&i.ScheduledStartTime,
		&i.ActualStartTime,
		&i.EndedAt,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostUsername,
		&i.PodSlug,
		&i.SkillSlug,
		&i.ChannelSlug,
	)
	return i, err
}

const listActiveAudioRooms = `-- name: ListActiveAudioRooms :many
SELECT
    id,
    public_id,
    livekit_room_name
FROM audio_room
WHERE status = 'ACTIVE'
ORDER BY id
`

type ListActiveAudioRoomsRow struct {
	ID              int64
	PublicID        uuid.UUID
	LivekitRoomName string
}

func (q *Queries) ListActiveAudioRooms(ctx context.Context) ([]ListActiveAudioRoomsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAudioRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAudioRoomsRow
	for rows.Next() {
		var i ListActiveAudioRoomsRow
		if err := rows.Scan(&i.ID, &i.PublicID, &i.LivekitRoomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioRoomsByChannelID = `-- name: ListAudioRoomsByChannelID :many
SELECT
    ar.id,
    ar.public_id,
    ar.room_type,
    ar.pod_id,
    ar.community_channel_id,
    ar.host_id,
    ar.title,
    ar.description,
    ar.livekit_room_name,
    ar.status,
    ar.scheduled_start_time,
    ar.actual_start_time,
    ar.ended_at,
    ar.max_participants,
    ar.created_at,
    ar.updated_at,
    u.username AS host_username
FROM audio_room ar
INNER JOIN users u ON u.id = ar.host_id
WHERE ar.community_channel_id = $1
  AND ($2::audio_room_status IS NULL OR ar.status = $2)
ORDER BY ar.created_at DESC
`

type ListAudioRoomsByChannelIDParams struct {
	ChannelID pgtype.Int8
	Status    NullAudioRoomStatus
}

type ListAudioRoomsByChannelIDRow struct {
	ID                 int64
	PublicID           uuid.UUID
	RoomType           AudioRoomType
	PodID              pgtype.Int8
	CommunityChannelID pgtype.Int8
	HostID             int64
	Title              string
	Description        pgtype.Text
	LivekitRoomName    string
	Status             AudioRoomStatus
	ScheduledStartTime pgtype.Timestamptz
	ActualStartTime    pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	MaxParticipants    pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	HostUsername       string
}

func (q *Queries) ListAudioRoomsByChannelID(ctx context.Context, arg ListAudioRoomsByChannelIDParams) ([]ListAudioRoomsByChannelIDRow, error) {
	rows, err := q.db.Query(ctx, listAudioRoomsByChannelID, arg.ChannelID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAudioRoomsByChannelIDRow
	for rows.Next() {
		var i ListAudioRoomsByChannelIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.RoomType,
			&i.PodID,
			&i.CommunityChannelID,
			&i.HostID,
			&i.Title,
			&i.Description,
			&i.LivekitRoomName,
			&i.Status,
			&i.ScheduledStartTime,
			&i.ActualStartTime,
			&i.EndedAt,
			&i.MaxParticipants,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioRoomsByPodID = `-- name: ListAudioRoomsByPodID :many
SELECT
    ar.id,
    ar.public_id,
    ar.room_type,
    ar.pod_id,
    ar.community_channel_id,
    ar.host_id,
    ar.title,
    ar.description,
    ar.livekit_room_name,
    ar.status,
    ar.scheduled_start_time,
    ar.actual_start_time,
    ar.ended_at,
    ar.max_participants,
    ar.created_at,
    ar.updated_at,
    u.username AS host_username
FROM audio_room ar
INNER JOIN users u ON u.id = ar.host_id
WHERE ar.pod_id = $1
  AND ($2::audio_room_status IS NULL OR ar.status = $2)
ORDER BY ar.created_at DESC
`

type ListAudioRoomsByPodIDParams struct {
	PodID  pgtype.Int8
	Status NullAudioRoomStatus
}

type ListAudioRoomsByPodIDRow struct {
	ID                 int64
	PublicID           uuid.UUID
	RoomType           AudioRoomType
	PodID              pgtype.Int8
	CommunityChannelID pgtype.Int8
	HostID             int64
	Title              string
	Description        pgtype.Text
	LivekitRoomName    string
	Status             AudioRoomStatus
	ScheduledStartTime pgtype.Timestamptz
	ActualStartTime    pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
	MaxParticipants    pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	HostUsername       string
}

func (q *Queries) ListAudioRoomsByPodID(ctx context.Context, arg ListAudioRoomsByPodIDParams) ([]ListAudioRoomsByPodIDRow, error) {
	rows, err := q.db.Query(ctx, listAudioRoomsByPodID, arg.PodID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAudioRoomsByPodIDRow
	for rows.Next() {
		var i ListAudioRoomsByPodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.RoomType,
			&i.PodID,
			&i.CommunityChannelID,
			&i.HostID,
			&i.Title,
			&i.Description,
			&i.LivekitRoomName,
			&i.Status,
			&i.ScheduledStartTime,
			&i.ActualStartTime,
			&i.EndedAt,
			&i.MaxParticipants,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleEmptyActiveAudioRooms = `-- name: ListStaleEmptyActiveAudioRooms :many
SELECT
    ar.id,
    ar.public_id,
    ar.livekit_room_name
FROM audio_room ar
WHERE ar.status = 'ACTIVE'
  AND NOT EXISTS (
      SELECT 1
      FROM audio_room_participant arp
      WHERE arp.audio_room_id = ar.id
        AND arp.left_at IS NULL
  )
  AND COALESCE(
      (
          SELECT MAX(arp.left_at)
          FROM audio_room_participant arp
          WHERE arp.audio_room_id = ar.id
      ),
      ar.actual_start_time,
      ar.created_at
  ) < $1
`

type ListStaleEmptyActiveAudioRoomsRow struct {
	ID              int64
	PublicID        uuid.UUID
	LivekitRoomName string
}

func (q *Queries) ListStaleEmptyActiveAudioRooms(ctx context.Context, emptyBefore pgtype.Timestamptz) ([]ListStaleEmptyActiveAudioRoomsRow, error) {
	rows, err := q.db.Query(ctx, listStaleEmptyActiveAudioRooms, emptyBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleEmptyActiveAudioRoomsRow
	for rows.Next() {
		var i ListStaleEmptyActiveAudioRoomsRow
		if err := rows.Scan(&i.ID, &i.PublicID, &i.LivekitRoomName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
