// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchCommunities = `-- name: SearchCommunities :many
SELECT
    c.id,
    c.skill_id,
    c.name,
    c.description,
    c.created_at,
    c.updated_at,
    s.slug AS skill_slug,
    s.name AS skill_name
FROM community c
INNER JOIN skills s ON s.id = c.skill_id
WHERE s.is_active = TRUE
  AND (
    c.name ILIKE '%' || $1::text || '%'
    OR s.name ILIKE '%' || $1::text || '%'
    OR s.slug ILIKE '%' || $1::text || '%'
  )
ORDER BY c.name
LIMIT $2
`

type SearchCommunitiesParams struct {
	Query string
	Lim   int32
}

type SearchCommunitiesRow struct {
	ID          int64
	SkillID     int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SkillSlug   string
	SkillName   string
}

func (q *Queries) SearchCommunities(ctx context.Context, arg SearchCommunitiesParams) ([]SearchCommunitiesRow, error) {
	rows, err := q.db.Query(ctx, searchCommunities, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCommunitiesRow
	for rows.Next() {
		var i SearchCommunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SkillSlug,
			&i.SkillName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkills = `-- name: SearchSkills :many

SELECT id, name, slug, description, is_active, created_at, updated_at
FROM skills
WHERE is_active = TRUE
  AND (
    name ILIKE '%' || $1::text || '%'
    OR slug ILIKE '%' || $1::text || '%'
  )
ORDER BY name
LIMIT $2
`

type SearchSkillsParams struct {
	Query string
	Lim   int32
}

// =========================================
// SEARCH
// =========================================
func (q *Queries) SearchSkills(ctx context.Context, arg SearchSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, searchSkills, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT public_id, username, name, profile_picture_url, bio
FROM users
WHERE is_deleted = FALSE
  AND username ILIKE '%' || $1::text || '%'
ORDER BY username
LIMIT $2
`

type SearchUsersParams struct {
	Query string
	Lim   int32
}

type SearchUsersRow struct {
	PublicID          uuid.UUID
	Username          string
	Name              string
	ProfilePictureUrl pgtype.Text
	Bio               pgtype.Text
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Username,
			&i.Name,
			&i.ProfilePictureUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
