// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package sqlc

import (
	"context"
)

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, name, slug, description, is_active, created_at, updated_at
FROM skills
WHERE id = $1
`

func (q *Queries) GetSkillByID(ctx context.Context, id int64) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByIDActive = `-- name: GetSkillByIDActive :one
SELECT id, name, slug, description, is_active, created_at, updated_at
FROM skills
WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) GetSkillByIDActive(ctx context.Context, id int64) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByIDActive, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillBySlug = `-- name: GetSkillBySlug :one
SELECT id, name, slug, description, is_active, created_at, updated_at
FROM skills
WHERE slug = $1
`

func (q *Queries) GetSkillBySlug(ctx context.Context, slug string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillBySlug, slug)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSkills = `-- name: ListActiveSkills :many

SELECT id, name, slug, description, is_active, created_at, updated_at
FROM skills
WHERE is_active = TRUE
ORDER BY name
`

// =========================================
// LIST / GET
// =========================================
func (q *Queries) ListActiveSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listActiveSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
