// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_creation_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveSkillCreationRequest = `-- name: ApproveSkillCreationRequest :one
UPDATE skill_creation_request
SET status = 'APPROVED',
    reviewed_by = $2,
    reviewed_at = NOW(),
    created_skill_id = $3,
    admin_note = $4,
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type ApproveSkillCreationRequestParams struct {
	ID             int64
	ReviewedBy     pgtype.Int8
	CreatedSkillID pgtype.Int8
	AdminNote      pgtype.Text
}

func (q *Queries) ApproveSkillCreationRequest(ctx context.Context, arg ApproveSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, approveSkillCreationRequest,
		arg.ID,
		arg.ReviewedBy,
		arg.CreatedSkillID,
		arg.AdminNote,
	)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const autoRejectGeneratingSkillCreationRequest = `-- name: AutoRejectGeneratingSkillCreationRequest :one
UPDATE skill_creation_request
SET status = 'REJECTED',
    reviewed_by = NULL,
    reviewed_at = NOW(),
    admin_note = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'GENERATING'
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type AutoRejectGeneratingSkillCreationRequestParams struct {
	ID        int64
	AdminNote pgtype.Text
}

func (q *Queries) AutoRejectGeneratingSkillCreationRequest(ctx context.Context, arg AutoRejectGeneratingSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, autoRejectGeneratingSkillCreationRequest, arg.ID, arg.AdminNote)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelSkillCreationRequest = `-- name: CancelSkillCreationRequest :one
UPDATE skill_creation_request
SET status = 'CANCELLED',
    updated_at = NOW()
WHERE public_id = $1
  AND requester_id = $2
  AND status IN ('PENDING', 'GENERATING')
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type CancelSkillCreationRequestParams struct {
	PublicID    uuid.UUID
	RequesterID int64
}

func (q *Queries) CancelSkillCreationRequest(ctx context.Context, arg CancelSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, cancelSkillCreationRequest, arg.PublicID, arg.RequesterID)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeSkillCreationDraft = `-- name: CompleteSkillCreationDraft :one
UPDATE skill_creation_request
SET draft_milestones = $2,
    status = 'PENDING',
    updated_at = NOW()
WHERE id = $1
  AND status = 'GENERATING'
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type CompleteSkillCreationDraftParams struct {
	ID              int64
	DraftMilestones []byte
}

func (q *Queries) CompleteSkillCreationDraft(ctx context.Context, arg CompleteSkillCreationDraftParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, completeSkillCreationDraft, arg.ID, arg.DraftMilestones)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkillCreationRequest = `-- name: CreateSkillCreationRequest :one
INSERT INTO skill_creation_request (
    requester_id,
    name,
    slug_candidate,
    description,
    status,
    similar_skills,
    draft_milestones
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type CreateSkillCreationRequestParams struct {
	RequesterID     int64
	Name            string
	SlugCandidate   string
	Description     pgtype.Text
	Status          CatalogRequestStatus
	SimilarSkills   []byte
	DraftMilestones []byte
}

func (q *Queries) CreateSkillCreationRequest(ctx context.Context, arg CreateSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, createSkillCreationRequest,
		arg.RequesterID,
		arg.Name,
		arg.SlugCandidate,
		arg.Description,
		arg.Status,
		arg.SimilarSkills,
		arg.DraftMilestones,
	)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSkillCreationRequest = `-- name: FailSkillCreationRequest :one
UPDATE skill_creation_request
SET status = 'FAILED',
    admin_note = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'GENERATING'
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type FailSkillCreationRequestParams struct {
	ID        int64
	AdminNote pgtype.Text
}

func (q *Queries) FailSkillCreationRequest(ctx context.Context, arg FailSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, failSkillCreationRequest, arg.ID, arg.AdminNote)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSkillCreationByRequesterAndName = `-- name: GetPendingSkillCreationByRequesterAndName :one
SELECT id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
FROM skill_creation_request
WHERE requester_id = $1
  AND lower(name) = lower($2)
  AND status IN ('PENDING', 'GENERATING')
LIMIT 1
`

type GetPendingSkillCreationByRequesterAndNameParams struct {
	RequesterID int64
	Lower       string
}

func (q *Queries) GetPendingSkillCreationByRequesterAndName(ctx context.Context, arg GetPendingSkillCreationByRequesterAndNameParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, getPendingSkillCreationByRequesterAndName, arg.RequesterID, arg.Lower)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillCreationRequestByID = `-- name: GetSkillCreationRequestByID :one
SELECT id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
FROM skill_creation_request
WHERE id = $1
`

func (q *Queries) GetSkillCreationRequestByID(ctx context.Context, id int64) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, getSkillCreationRequestByID, id)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillCreationRequestByPublicID = `-- name: GetSkillCreationRequestByPublicID :one
SELECT id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
FROM skill_creation_request
WHERE public_id = $1
`

func (q *Queries) GetSkillCreationRequestByPublicID(ctx context.Context, publicID uuid.UUID) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, getSkillCreationRequestByPublicID, publicID)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGeneratingSkillCreationRequests = `-- name: ListGeneratingSkillCreationRequests :many
SELECT id
FROM skill_creation_request
WHERE status = 'GENERATING'
ORDER BY created_at ASC
`

func (q *Queries) ListGeneratingSkillCreationRequests(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGeneratingSkillCreationRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSkillCreationRequests = `-- name: ListPendingSkillCreationRequests :many
SELECT id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
FROM skill_creation_request
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingSkillCreationRequests(ctx context.Context, resultLimit int32) ([]SkillCreationRequest, error) {
	rows, err := q.db.Query(ctx, listPendingSkillCreationRequests, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillCreationRequest
	for rows.Next() {
		var i SkillCreationRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.RequesterID,
			&i.Name,
			&i.SlugCandidate,
			&i.Description,
			&i.Status,
			&i.SimilarSkills,
			&i.DraftMilestones,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedSkillID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillCreationRequestsByRequester = `-- name: ListSkillCreationRequestsByRequester :many
SELECT id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
FROM skill_creation_request
WHERE requester_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListSkillCreationRequestsByRequesterParams struct {
	RequesterID int64
	ResultLimit int32
}

func (q *Queries) ListSkillCreationRequestsByRequester(ctx context.Context, arg ListSkillCreationRequestsByRequesterParams) ([]SkillCreationRequest, error) {
	rows, err := q.db.Query(ctx, listSkillCreationRequestsByRequester, arg.RequesterID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillCreationRequest
	for rows.Next() {
		var i SkillCreationRequest
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.RequesterID,
			&i.Name,
			&i.SlugCandidate,
			&i.Description,
			&i.Status,
			&i.SimilarSkills,
			&i.DraftMilestones,
			&i.AdminNote,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedSkillID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectSkillCreationRequest = `-- name: RejectSkillCreationRequest :one
UPDATE skill_creation_request
SET status = 'REJECTED',
    reviewed_by = $2,
    reviewed_at = NOW(),
    admin_note = $3,
    updated_at = NOW()
WHERE id = $1
  AND status = 'PENDING'
RETURNING id, public_id, requester_id, name, slug_candidate, description, status, similar_skills, draft_milestones, admin_note, reviewed_by, reviewed_at, created_skill_id, created_at, updated_at
`

type RejectSkillCreationRequestParams struct {
	ID         int64
	ReviewedBy pgtype.Int8
	AdminNote  pgtype.Text
}

func (q *Queries) RejectSkillCreationRequest(ctx context.Context, arg RejectSkillCreationRequestParams) (SkillCreationRequest, error) {
	row := q.db.QueryRow(ctx, rejectSkillCreationRequest, arg.ID, arg.ReviewedBy, arg.AdminNote)
	var i SkillCreationRequest
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RequesterID,
		&i.Name,
		&i.SlugCandidate,
		&i.Description,
		&i.Status,
		&i.SimilarSkills,
		&i.DraftMilestones,
		&i.AdminNote,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedSkillID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
