// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streak.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStreak = `-- name: CreateStreak :one

INSERT INTO streak (
    user_id,
    current_streak,
    longest_streak,
    last_activity_date
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, current_streak, longest_streak, last_activity_date, freeze_count, updated_at
`

type CreateStreakParams struct {
	UserID           pgtype.Int8
	CurrentStreak    int32
	LongestStreak    int32
	LastActivityDate pgtype.Date
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateStreak(ctx context.Context, arg CreateStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, createStreak,
		arg.UserID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActivityDate,
	)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.FreezeCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getStreakByUserID = `-- name: GetStreakByUserID :one

SELECT id, user_id, current_streak, longest_streak, last_activity_date, freeze_count, updated_at
FROM streak
WHERE user_id = $1
`

// =========================================
// GET
// =========================================
func (q *Queries) GetStreakByUserID(ctx context.Context, userID pgtype.Int8) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreakByUserID, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.FreezeCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getStreakByUserIDForUpdate = `-- name: GetStreakByUserIDForUpdate :one
SELECT id, user_id, current_streak, longest_streak, last_activity_date, freeze_count, updated_at
FROM streak
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetStreakByUserIDForUpdate(ctx context.Context, userID pgtype.Int8) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreakByUserIDForUpdate, userID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.FreezeCount,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStreak = `-- name: UpdateStreak :one

UPDATE streak
SET
    current_streak = $2,
    longest_streak = $3,
    last_activity_date = $4,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, current_streak, longest_streak, last_activity_date, freeze_count, updated_at
`

type UpdateStreakParams struct {
	UserID           pgtype.Int8
	CurrentStreak    int32
	LongestStreak    int32
	LastActivityDate pgtype.Date
}

// =========================================
// UPDATE
// =========================================
func (q *Queries) UpdateStreak(ctx context.Context, arg UpdateStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, updateStreak,
		arg.UserID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActivityDate,
	)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.FreezeCount,
		&i.UpdatedAt,
	)
	return i, err
}
