// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudySession = `-- name: CreateStudySession :one

INSERT INTO study_session (
    user_id,
    skill_id,
    duration_minutes,
    notes,
    studied_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, skill_id, duration_minutes, notes, studied_at, created_at
`

type CreateStudySessionParams struct {
	UserID          pgtype.Int8
	SkillID         pgtype.Int8
	DurationMinutes int32
	Notes           pgtype.Text
	StudiedAt       pgtype.Timestamptz
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, createStudySession,
		arg.UserID,
		arg.SkillID,
		arg.DurationMinutes,
		arg.Notes,
		arg.StudiedAt,
	)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.DurationMinutes,
		&i.Notes,
		&i.StudiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listStudySessionsByUserAndSkillSlug = `-- name: ListStudySessionsByUserAndSkillSlug :many
SELECT ss.id, ss.user_id, ss.skill_id, ss.duration_minutes, ss.notes, ss.studied_at, ss.created_at,
       s.slug AS skill_slug
FROM study_session ss
INNER JOIN skills s ON s.id = ss.skill_id
WHERE ss.user_id = $1
  AND s.slug = $2
ORDER BY ss.studied_at DESC
`

type ListStudySessionsByUserAndSkillSlugParams struct {
	UserID pgtype.Int8
	Slug   string
}

type ListStudySessionsByUserAndSkillSlugRow struct {
	ID              int64
	UserID          pgtype.Int8
	SkillID         pgtype.Int8
	DurationMinutes int32
	Notes           pgtype.Text
	StudiedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	SkillSlug       string
}

func (q *Queries) ListStudySessionsByUserAndSkillSlug(ctx context.Context, arg ListStudySessionsByUserAndSkillSlugParams) ([]ListStudySessionsByUserAndSkillSlugRow, error) {
	rows, err := q.db.Query(ctx, listStudySessionsByUserAndSkillSlug, arg.UserID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudySessionsByUserAndSkillSlugRow
	for rows.Next() {
		var i ListStudySessionsByUserAndSkillSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillID,
			&i.DurationMinutes,
			&i.Notes,
			&i.StudiedAt,
			&i.CreatedAt,
			&i.SkillSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudySessionsByUserID = `-- name: ListStudySessionsByUserID :many

SELECT ss.id, ss.user_id, ss.skill_id, ss.duration_minutes, ss.notes, ss.studied_at, ss.created_at,
       s.slug AS skill_slug
FROM study_session ss
INNER JOIN skills s ON s.id = ss.skill_id
WHERE ss.user_id = $1
ORDER BY ss.studied_at DESC
`

type ListStudySessionsByUserIDRow struct {
	ID              int64
	UserID          pgtype.Int8
	SkillID         pgtype.Int8
	DurationMinutes int32
	Notes           pgtype.Text
	StudiedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	SkillSlug       string
}

// =========================================
// GET
// =========================================
func (q *Queries) ListStudySessionsByUserID(ctx context.Context, userID pgtype.Int8) ([]ListStudySessionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listStudySessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudySessionsByUserIDRow
	for rows.Next() {
		var i ListStudySessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillID,
			&i.DurationMinutes,
			&i.Notes,
			&i.StudiedAt,
			&i.CreatedAt,
			&i.SkillSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumStudyMinutesByUserID = `-- name: SumStudyMinutesByUserID :one
SELECT COALESCE(SUM(duration_minutes), 0)::bigint
FROM study_session
WHERE user_id = $1
`

func (q *Queries) SumStudyMinutesByUserID(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, sumStudyMinutesByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumStudyMinutesLast7Days = `-- name: SumStudyMinutesLast7Days :one
SELECT COALESCE(SUM(duration_minutes), 0)::bigint
FROM study_session
WHERE user_id = $1
  AND studied_at >= NOW() - INTERVAL '7 days'
`

func (q *Queries) SumStudyMinutesLast7Days(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, sumStudyMinutesLast7Days, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumStudyMinutesThisMonth = `-- name: SumStudyMinutesThisMonth :one
SELECT COALESCE(SUM(duration_minutes), 0)::bigint
FROM study_session
WHERE user_id = $1
  AND studied_at >= date_trunc('month', NOW())
`

func (q *Queries) SumStudyMinutesThisMonth(ctx context.Context, userID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, sumStudyMinutesThisMonth, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
