// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one

INSERT INTO user_identity (
    user_id,
    provider,
    provider_user_id,
    password_hash
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID         int64
	Provider       ProviderName
	ProviderUserID pgtype.Text
	PasswordHash   pgtype.Text
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.PasswordHash,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one

SELECT id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
FROM user_identity
WHERE id = $1
`

// =========================================
// GET
// =========================================
func (q *Queries) GetIdentityByID(ctx context.Context, id int64) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByProvider = `-- name: GetIdentityByProvider :one
SELECT id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
FROM user_identity
WHERE user_id = $1
  AND provider = $2
`

type GetIdentityByProviderParams struct {
	UserID   int64
	Provider ProviderName
}

func (q *Queries) GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProvider, arg.UserID, arg.Provider)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByProviderUserID = `-- name: GetIdentityByProviderUserID :one
SELECT id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
FROM user_identity
WHERE provider = $1
  AND provider_user_id = $2
`

type GetIdentityByProviderUserIDParams struct {
	Provider       ProviderName
	ProviderUserID pgtype.Text
}

func (q *Queries) GetIdentityByProviderUserID(ctx context.Context, arg GetIdentityByProviderUserIDParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderUserID, arg.Provider, arg.ProviderUserID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByUserID = `-- name: GetIdentityByUserID :many
SELECT id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
FROM user_identity
WHERE user_id = $1
`

func (q *Queries) GetIdentityByUserID(ctx context.Context, userID int64) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, getIdentityByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one

UPDATE user_identity
SET
    password_hash = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
`

type UpdatePasswordHashParams struct {
	ID           int64
	PasswordHash pgtype.Text
}

// =========================================
// UPDATE
// =========================================
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderUserID = `-- name: UpdateProviderUserID :one
UPDATE user_identity
SET
    provider_user_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, provider, provider_user_id, password_hash, created_at, updated_at
`

type UpdateProviderUserIDParams struct {
	ID             int64
	ProviderUserID pgtype.Text
}

func (q *Queries) UpdateProviderUserID(ctx context.Context, arg UpdateProviderUserIDParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, updateProviderUserID, arg.ID, arg.ProviderUserID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
