// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    public_id,
    email,
    username,
    name,
    profile_picture_url,
    bio,
    subscription,
    email_verified,
    is_deleted,
    deleted_at,
    created_at,
    updated_at
FROM users
WHERE email = $1 AND is_deleted = FALSE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.ProfilePictureUrl,
		&i.Bio,
		&i.Subscription,
		&i.EmailVerified,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
