// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: userskill.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUserSkillsByUserID = `-- name: CountActiveUserSkillsByUserID :one

SELECT COUNT(*)::bigint
FROM userskill
WHERE user_id = $1
  AND status = 'ACTIVE'
`

// =========================================
// GET
// =========================================
func (q *Queries) CountActiveUserSkillsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserSkillsByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUserSkill = `-- name: CreateUserSkill :one

INSERT INTO userskill (
    user_id,
    skill_id,
    roadmap_version_id,
    status
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, skill_id, roadmap_version_id, status, started_at, completed_at
`

type CreateUserSkillParams struct {
	UserID           int64
	SkillID          int64
	RoadmapVersionID int64
	Status           StatusValue
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateUserSkill(ctx context.Context, arg CreateUserSkillParams) (Userskill, error) {
	row := q.db.QueryRow(ctx, createUserSkill,
		arg.UserID,
		arg.SkillID,
		arg.RoadmapVersionID,
		arg.Status,
	)
	var i Userskill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.RoadmapVersionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserSkillByID = `-- name: GetUserSkillByID :one
SELECT id, user_id, skill_id, roadmap_version_id, status, started_at, completed_at
FROM userskill
WHERE id = $1
  AND user_id = $2
`

type GetUserSkillByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetUserSkillByID(ctx context.Context, arg GetUserSkillByIDParams) (Userskill, error) {
	row := q.db.QueryRow(ctx, getUserSkillByID, arg.ID, arg.UserID)
	var i Userskill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.RoadmapVersionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserSkillByUserAndSkill = `-- name: GetUserSkillByUserAndSkill :one
SELECT id, user_id, skill_id, roadmap_version_id, status, started_at, completed_at
FROM userskill
WHERE user_id = $1
  AND skill_id = $2
`

type GetUserSkillByUserAndSkillParams struct {
	UserID  int64
	SkillID int64
}

func (q *Queries) GetUserSkillByUserAndSkill(ctx context.Context, arg GetUserSkillByUserAndSkillParams) (Userskill, error) {
	row := q.db.QueryRow(ctx, getUserSkillByUserAndSkill, arg.UserID, arg.SkillID)
	var i Userskill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.RoadmapVersionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserSkillByUserAndSkillSlug = `-- name: GetUserSkillByUserAndSkillSlug :one
SELECT us.id, us.user_id, us.skill_id, us.roadmap_version_id, us.status, us.started_at, us.completed_at
FROM userskill us
INNER JOIN skills s ON s.id = us.skill_id
WHERE us.user_id = $1
  AND s.slug = $2
`

type GetUserSkillByUserAndSkillSlugParams struct {
	UserID int64
	Slug   string
}

func (q *Queries) GetUserSkillByUserAndSkillSlug(ctx context.Context, arg GetUserSkillByUserAndSkillSlugParams) (Userskill, error) {
	row := q.db.QueryRow(ctx, getUserSkillByUserAndSkillSlug, arg.UserID, arg.Slug)
	var i Userskill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.RoadmapVersionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listUserSkillsByUserID = `-- name: ListUserSkillsByUserID :many
SELECT us.id, us.user_id, us.skill_id, us.roadmap_version_id, us.status, us.started_at, us.completed_at,
       s.name AS skill_name, s.slug AS skill_slug,
       rv.version_number AS roadmap_version_number,
       rv.status AS roadmap_version_status,
       (
           SELECT COUNT(*)::bigint
           FROM user_milestone_progress ump
           WHERE ump.user_skill_id = us.id
       ) AS milestone_count,
       (
           SELECT COUNT(*)::bigint
           FROM user_milestone_progress ump
           WHERE ump.user_skill_id = us.id
             AND ump.status = 'COMPLETED'
       ) AS completed_count
FROM userskill us
INNER JOIN skills s ON s.id = us.skill_id
INNER JOIN roadmap_version rv ON rv.id = us.roadmap_version_id
WHERE us.user_id = $1
ORDER BY us.started_at DESC
`

type ListUserSkillsByUserIDRow struct {
	ID                   int64
	UserID               int64
	SkillID              int64
	RoadmapVersionID     int64
	Status               StatusValue
	StartedAt            pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	SkillName            string
	SkillSlug            string
	RoadmapVersionNumber int32
	RoadmapVersionStatus CurrentStatus
	MilestoneCount       int64
	CompletedCount       int64
}

func (q *Queries) ListUserSkillsByUserID(ctx context.Context, userID int64) ([]ListUserSkillsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listUserSkillsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSkillsByUserIDRow
	for rows.Next() {
		var i ListUserSkillsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SkillID,
			&i.RoadmapVersionID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.SkillName,
			&i.SkillSlug,
			&i.RoadmapVersionNumber,
			&i.RoadmapVersionStatus,
			&i.MilestoneCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSkillRoadmapVersion = `-- name: UpdateUserSkillRoadmapVersion :one

UPDATE userskill
SET roadmap_version_id = $2
WHERE id = $1
RETURNING id, user_id, skill_id, roadmap_version_id, status, started_at, completed_at
`

type UpdateUserSkillRoadmapVersionParams struct {
	ID               int64
	RoadmapVersionID int64
}

// =========================================
// UPDATE
// =========================================
func (q *Queries) UpdateUserSkillRoadmapVersion(ctx context.Context, arg UpdateUserSkillRoadmapVersionParams) (Userskill, error) {
	row := q.db.QueryRow(ctx, updateUserSkillRoadmapVersion, arg.ID, arg.RoadmapVersionID)
	var i Userskill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkillID,
		&i.RoadmapVersionID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
