// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO user_sessions (
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, public_id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID           int64
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        *netip.Addr
	ExpiresAt        pgtype.Timestamptz
}

// =========================================
// CREATE
// =========================================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec

DELETE FROM user_sessions
WHERE refresh_token_hash = $1
`

// =========================================
// DELETE
// =========================================
func (q *Queries) DeleteSession(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, refreshTokenHash)
	return err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one

SELECT id, public_id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, updated_at
FROM user_sessions
WHERE refresh_token_hash = $1
`

// =========================================
// GET
// =========================================
func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one

UPDATE user_sessions
SET
    refresh_token_hash = $2,
    expires_at = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, public_id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, revoked_at, created_at, updated_at
`

type RotateRefreshTokenParams struct {
	ID               int64
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

// =========================================
// UPDATE
// =========================================
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
