// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: username_history.sql

package sqlc

import (
	"context"
)

const createUsernameHistory = `-- name: CreateUsernameHistory :one
INSERT INTO username_history (
    user_id,
    username
)
VALUES (
    $1,
    $2
)
RETURNING id, user_id, username, created_at
`

type CreateUsernameHistoryParams struct {
	UserID   int64
	Username string
}

func (q *Queries) CreateUsernameHistory(ctx context.Context, arg CreateUsernameHistoryParams) (UsernameHistory, error) {
	row := q.db.QueryRow(ctx, createUsernameHistory, arg.UserID, arg.Username)
	var i UsernameHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
